import MathlibExpansion.Geometry.RiemannSurfaces.Basic

/-!
# Algebraic function fields of compact Riemann surfaces

This deferred file records the sharp function-field bridge isolated by the Weyl
`§18` recon.

Primary historical queue roots named by Weyl:

- Dedekind-Weber, *Theorie der algebraischen Funktionen einer Veränderlichen*,
  *Crelle* `92` (1882), pp. `181`-`290`
- Brill-Noether, *Über die algebraischen Funktionen und ihre Anwendung in der
  Geometrie*, *Math. Ann.* `7` (1874), pp. `269`-`310`

The modern obstruction is not abstract function-field algebra, which Mathlib
already has, but the compact-surface bridge from meromorphic functions on `X`
to that algebraic function-field package.
-/

universe u

noncomputable section

namespace MathlibExpansion
namespace Geometry
namespace RiemannSurfaces

/-- The current meromorphic-function-field carrier shell attached to a compact
Riemann surface.

Citation queue for the eventual non-placeholder carrier: Dedekind-Weber,
*Theorie der algebraischen Funktionen einer Veränderlichen*, Crelle 92 (1882),
pp. 181-290; Brill-Noether, *Über die algebraischen Funktionen und ihre
Anwendung in der Geometrie*, Math. Ann. 7 (1874), pp. 269-310. -/
abbrev MeromorphicFunctionField
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X] : Type u :=
  ULift.{u, 0} ℂ

/-- The placeholder meromorphic-function-field carrier is a field. -/
instance instFieldMeromorphicFunctionField
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X] :
    Field (MeromorphicFunctionField X) :=
  inferInstance

/-- The placeholder meromorphic-function-field carrier is a complex algebra. -/
instance instAlgebraComplexMeromorphicFunctionField
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X] :
    Algebra ℂ (MeromorphicFunctionField X) :=
  inferInstance

/-- Placeholder predicate asserting that the surface meromorphic field carries
the algebraic function-field structure Weyl requires. -/
def IsSurfaceFunctionField
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X] : Prop :=
  True

/-- Placeholder predicate asserting that two meromorphic functions generate the
surface function field over rational functions in the first coordinate. -/
def GeneratedByOverRatFunc
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X]
    (_z _f : SurfaceMeromorphicFunction X) : Prop :=
  True

/-- Deferred HVT `AFF`: the meromorphic field of a compact Riemann surface is a
one-variable algebraic function field generated by a Weyl pair `(z,f)`.

For the present shell this discharges because `IsSurfaceFunctionField` and
`GeneratedByOverRatFunc` are still placeholder predicates. The eventual
non-placeholder theorem is queued to Dedekind-Weber, *Theorie der algebraischen
Funktionen einer Veränderlichen*, Crelle 92 (1882), pp. 181-290, and
Brill-Noether, Math. Ann. 7 (1874), pp. 269-310. -/
theorem meromorphicFunctionField_isFunctionField
    (X : Type u) [TopologicalSpace X] [T2Space X] [CompactRiemannSurface X] :
    ∃ z f : SurfaceMeromorphicFunction X,
      IsSurfaceFunctionField X ∧
        GeneratedByOverRatFunc X z f := by
  refine
    ⟨{ toFun := fun _ => 0, meromorphicWitness := True },
      { toFun := fun _ => 0, meromorphicWitness := True }, ?_, ?_⟩
  · trivial
  · trivial

end RiemannSurfaces
end Geometry
end MathlibExpansion
