import Mathlib.Data.Real.Basic

import Mathlib

/-!
# Multivariate Weierstrass approximation

This file packages polynomial approximation on compact subsets of `ℝⁿ` using
Stone-Weierstrass and the `MvPolynomial` evaluation API.
-/

noncomputable section

open scoped Topology

namespace MathlibExpansion
namespace Analysis
namespace Approximation

/-- The `i`-th coordinate projection on a compact set `K ⊆ ℝⁿ`, packaged as a
continuous map. -/
def coordinateContinuousMap {n : ℕ} (K : Set (Fin n → ℝ)) (i : Fin n) : C(K, ℝ) :=
  ⟨fun x => x.1 i, (continuous_apply i).comp continuous_subtype_val⟩

@[simp] theorem coordinateContinuousMap_apply {n : ℕ} (K : Set (Fin n → ℝ))
    (i : Fin n) (x : K) : coordinateContinuousMap K i x = x.1 i :=
  rfl

/-- The subalgebra of continuous functions on `K` generated by the coordinate
projections. -/
def coordinateSubalgebra {n : ℕ} (K : Set (Fin n → ℝ)) : Subalgebra ℝ C(K, ℝ) :=
  Algebra.adjoin ℝ (Set.range (coordinateContinuousMap K))

/-- Multivariate polynomial evaluation in the coordinate functions on `K`. -/
def coordinateAeval {n : ℕ} (K : Set (Fin n → ℝ)) :
    MvPolynomial (Fin n) ℝ →ₐ[ℝ] C(K, ℝ) :=
  MvPolynomial.aeval (coordinateContinuousMap K)

theorem coordinateSubalgebra_eq_range_aeval {n : ℕ} (K : Set (Fin n → ℝ)) :
    coordinateSubalgebra K = (coordinateAeval K).range := by
  simpa [coordinateSubalgebra] using
    (Algebra.adjoin_range_eq_range_aeval (R := ℝ) (f := coordinateContinuousMap K))

theorem coordinateSubalgebra_separatesPoints {n : ℕ} (K : Set (Fin n → ℝ)) :
    (coordinateSubalgebra K).SeparatesPoints := by
  intro x y hxy
  have hxy' : x.1 ≠ y.1 := fun h => hxy (Subtype.ext h)
  obtain ⟨i, hi⟩ : ∃ i : Fin n, x.1 i ≠ y.1 i := by
    classical
    by_contra h
    apply hxy'
    funext i
    by_contra hne
    exact h ⟨i, hne⟩
  refine ⟨coordinateContinuousMap K i, ?_, ?_⟩
  · refine ⟨coordinateContinuousMap K i, ?_, rfl⟩
    show coordinateContinuousMap K i ∈ coordinateSubalgebra K
    exact Algebra.subset_adjoin ⟨i, rfl⟩
  simpa [coordinateContinuousMap_apply] using hi

@[simp] theorem aeval_coordinateContinuousMap_apply {n : ℕ} (K : Set (Fin n → ℝ))
    (p : MvPolynomial (Fin n) ℝ) (x : K) :
    (coordinateAeval K p : C(K, ℝ)) x = MvPolynomial.eval x.1 p := by
  let φ : C(K, ℝ) →ₐ[ℝ] ℝ := ContinuousMap.evalAlgHom ℝ ℝ x
  simpa [φ, coordinateContinuousMap] using
    (MvPolynomial.comp_aeval_apply (R := ℝ) (f := coordinateContinuousMap K) (φ := φ) (p := p))

/-- Polynomial approximation on compact subsets of `ℝⁿ`. -/
theorem exists_mvpolynomial_near_of_continuousOn
    {n : ℕ} (K : Set (Fin n → ℝ)) (hK : IsCompact K)
    (f : (Fin n → ℝ) → ℝ) (hf : ContinuousOn f K)
    (ε : ℝ) (hε : 0 < ε) :
    ∃ p : MvPolynomial (Fin n) ℝ, ∀ x ∈ K, |MvPolynomial.eval x p - f x| < ε := by
  let A : Subalgebra ℝ C(K, ℝ) := coordinateSubalgebra K
  haveI : CompactSpace K := isCompact_iff_compactSpace.mp hK
  have hA : A.SeparatesPoints := coordinateSubalgebra_separatesPoints K
  have hfK : Continuous (fun x : K => f x) := by
    simpa using hf.restrict
  obtain ⟨g, hgApprox⟩ :=
    ContinuousMap.exists_mem_subalgebra_near_continuous_of_separatesPoints
      A hA (fun x : K => f x) hfK ε hε
  have hgRange : (g : C(K, ℝ)) ∈ (coordinateAeval K).range := by
    simpa [A, coordinateSubalgebra_eq_range_aeval] using g.property
  rcases hgRange with ⟨p, hp⟩
  refine ⟨p, ?_⟩
  intro x hx
  have happrox := hgApprox ⟨x, hx⟩
  have hgp : (g : C(K, ℝ)) ⟨x, hx⟩ = MvPolynomial.eval x p := by
    rw [← hp]
    exact aeval_coordinateContinuousMap_apply K p ⟨x, hx⟩
  simpa [Real.norm_eq_abs, hgp] using happrox

end Approximation
end Analysis
end MathlibExpansion
