import Mathlib.Data.Setoid.Basic
import Mathlib.Geometry.Manifold.Diffeomorph
import Mathlib.Geometry.Manifold.IsManifold.Basic
import Mathlib.Topology.Constructions

namespace MathlibExpansion
namespace Geometry
namespace Manifold

open scoped ContDiff Manifold

universe u

/-- Smooth self-diffeomorphisms of a `2`-manifold, expressed using Mathlib's
`Diffeomorph` API. This is the self-map input for Poincare's suspension
examples in *Analysis Situs* (1895), Section 11. -/
abbrev CInfinityDiffeomorph
    (X : Type u) [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X] : Type u :=
  Diffeomorph (modelWithCornersSelf ℝ (Fin 2 → ℝ))
    (modelWithCornersSelf ℝ (Fin 2 → ℝ)) X X ∞

/-- The one-step suspension relation `(x,t) ~ (f x,t+1)` used to define the
mapping torus quotient. Poincare's torus-suspension examples appear in
*Analysis Situs* (1895), Section 11. -/
def mappingTorusStep
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    (f : CInfinityDiffeomorph X) : X × ℝ → X × ℝ → Prop :=
  fun p q => q = (f p.1, p.2 + 1)

/-- The equivalence relation generated by the suspension step
`(x,t) ~ (f x,t+1)`. This is the concrete quotient relation underlying the
mapping torus construction in Poincare, *Analysis Situs* (1895), Section 11. -/
def mappingTorusSetoid
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    (f : CInfinityDiffeomorph X) : Setoid (X × ℝ) :=
  Relation.EqvGen.setoid (mappingTorusStep f)

/-- The mapping torus carrier attached to a smooth self-diffeomorphism: the
quotient of `X × ℝ` by `(x,t) ~ (f x,t+1)`. This is the suspension construction
Poincare uses in *Analysis Situs* (1895), Section 11. -/
def MappingTorus
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    (f : CInfinityDiffeomorph X) : Type u :=
  Quotient (mappingTorusSetoid f)

/-- The quotient topology on the mapping torus, induced from `X × ℝ`. -/
noncomputable instance instTopologicalSpaceMappingTorus
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    (f : CInfinityDiffeomorph X) :
    TopologicalSpace (MappingTorus f) :=
  inferInstanceAs (TopologicalSpace (Quotient (mappingTorusSetoid f)))

/-- Smooth quotient-manifold data for the mapping torus of a smooth
self-diffeomorphism of a smooth surface. This is the remaining upstream
boundary: Poincare's suspension examples in *Analysis Situs* (1895), Section 11
require the modern theorem that the quotient of `X × ℝ` by
`(x,t) ~ (f x,t+1)` inherits a smooth `3`-manifold atlas. -/
structure MappingTorusSmoothStructure
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    [IsManifold (modelWithCornersSelf ℝ (Fin 2 → ℝ)) ∞ X]
    (f : CInfinityDiffeomorph X) :
    Type u where
  chartedSpace : ChartedSpace (Fin 3 → ℝ) (MappingTorus f)
  isManifold :
    letI := chartedSpace
    IsManifold (modelWithCornersSelf ℝ (Fin 3 → ℝ)) ∞ (MappingTorus f)

/-- Upstream quotient-manifold theorem for mapping tori. Exact source anchor:
Poincare, *Analysis Situs* (1895), Section 11, where the torus-suspension
example family is introduced; the original article is section-numbered rather
than theorem-numbered. The missing modern substrate is the smooth quotient
atlas for the generated `ℤ`-action on `X × ℝ`. -/
axiom mappingTorusSmoothStructure
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    [IsManifold (modelWithCornersSelf ℝ (Fin 2 → ℝ)) ∞ X]
    (f : CInfinityDiffeomorph X) :
    MappingTorusSmoothStructure f

/-- Smooth `3`-dimensional charted-space structure on a mapping torus, extracted
from the single quotient-manifold boundary above. -/
noncomputable instance instChartedSpaceMappingTorus
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    [IsManifold (modelWithCornersSelf ℝ (Fin 2 → ℝ)) ∞ X]
    (f : CInfinityDiffeomorph X) :
    ChartedSpace (Fin 3 → ℝ) (MappingTorus f) :=
  (mappingTorusSmoothStructure f).chartedSpace

/-- Poincare's mapping-torus example family forms `3`-manifolds. This theorem
now follows from the single smooth quotient-structure boundary above; see
Poincare, *Analysis Situs* (1895), Section 11. -/
theorem isManifold_mappingTorus
    {X : Type u} [TopologicalSpace X] [ChartedSpace (Fin 2 → ℝ) X]
    [IsManifold (modelWithCornersSelf ℝ (Fin 2 → ℝ)) ∞ X]
    (f : CInfinityDiffeomorph X) :
    IsManifold (modelWithCornersSelf ℝ (Fin 3 → ℝ)) ∞ (MappingTorus f) :=
  (mappingTorusSmoothStructure f).isManifold

end Manifold
end Geometry
end MathlibExpansion
