import MathlibExpansion.Roots.Iwasawa.Elementary

/-!
# Characteristic Ideal of an Iwasawa module

This file develops the theory of the **characteristic ideal** `char(M)` of a
finitely generated `Λ = ℤ_p[[T]]`-module at the profile level.

## Profile-level characteristic ideal

Given a `LambdaElementaryProfile p`, the characteristic element is

  `char_elem(P) = p^μ · ∏_j D_j ∈ Λ`

and the characteristic ideal is `char(P) = (char_elem(P)) ⊆ Λ`.

Both are defined in `Elementary.lean`; this file proves their structural
properties:

- **Multiplicativity** under profile concatenation (`append`)
- **Single-factor** evaluations (μ-pure and λ-pure profiles)
- **Free profile**: `char(Λ^r) = (1) = ⊤`
- **Honest gap wall**: uniqueness of the characteristic ideal as a module
  invariant requires `iwasawaStructureTheorem` (see `StructureTheorem.lean`).
  At the profile level, the ideal is well-defined but not yet shown independent
  of the pseudo-isomorphism class.

## Notation

We write `charElem P` for `P.characteristicElement` and `charIdeal P` for
`P.characteristicIdeal`.

## References

- Washington, *Introduction to Cyclotomic Fields*, §13.2
- Neukirch-Schmidt-Wingberg, *Cohomology of Number Fields*, §5.3
- Bourbaki, *Commutative Algebra* VII §4.4
-/

namespace MathlibExpansion
namespace Roots
namespace Iwasawa

open scoped Padic
open LambdaElementaryProfile

variable {p : ℕ} [Fact p.Prime]

/-! ## Abbreviations -/

/-- Shorthand for the characteristic element of a profile. -/
noncomputable abbrev charElem (P : LambdaElementaryProfile p) : Lambda ℤ_[p] :=
  P.characteristicElement

/-- Shorthand for the characteristic ideal of a profile. -/
noncomputable abbrev charIdeal (P : LambdaElementaryProfile p) : Ideal (Lambda ℤ_[p]) :=
  P.characteristicIdeal

/-! ## Characteristic element is nonzero (at the profile level)

We cannot prove this without knowing `primeInLambda p ≠ 0` and that
distinguished polynomials are nonzero as power series.  We record both
as honest lemmas using what is available. -/

theorem charElem_singlePPower_eq (n : ℕ) :
    charElem (singlePPowerProfile (p := p) n) = primeInLambda p ^ n := by
  simp [charElem, singlePPowerProfile_characteristicElement]

theorem charElem_singleDistinguished_eq (D : DistinguishedPolynomial p) :
    charElem (singleDistinguishedProfile D) = D.toPowerSeries := by
  simp [charElem, singleDistinguishedProfile_characteristicElement]

/-! ## Multiplicativity of the characteristic element -/

/-- The characteristic element is multiplicative under profile concatenation. -/
theorem charElem_append (P Q : LambdaElementaryProfile p) :
    charElem (P.append Q) = charElem P * charElem Q :=
  append_characteristicElement P Q

/-- The characteristic ideal is generated by the product of characteristic
elements under profile concatenation. -/
theorem charIdeal_append_eq_span_mul (P Q : LambdaElementaryProfile p) :
    charIdeal (P.append Q) =
      Ideal.span ({charElem P * charElem Q} : Set (Lambda ℤ_[p])) := by
  rw [charIdeal, append_characteristicIdeal_generator]

/-! ## Free and trivial profiles -/

/-- The free profile Λ^r has characteristic element 1 (μ = 0, no distinguished factors). -/
theorem charElem_free_eq_one (rank : ℕ) :
    charElem (freeLambdaElementaryProfile p rank) = 1 := by
  unfold charElem LambdaElementaryProfile.characteristicElement freeLambdaElementaryProfile
  simp [LambdaElementaryProfile.mu]

/-- The characteristic ideal of the free profile is ⊤ = (1). -/
theorem charIdeal_free_eq_top (rank : ℕ) :
    charIdeal (freeLambdaElementaryProfile p rank) = ⊤ := by
  rw [charIdeal, LambdaElementaryProfile.characteristicIdeal]
  rw [show (freeLambdaElementaryProfile p rank).characteristicElement = 1 from
        charElem_free_eq_one rank]
  simp [Ideal.span_singleton_eq_top]

/-- A profile with isUnit characteristic element has trivial characteristic ideal. -/
theorem charIdeal_eq_top_of_isUnit (P : LambdaElementaryProfile p)
    (h : IsUnit (charElem P)) : charIdeal P = ⊤ :=
  characteristicIdeal_eq_top_of_isUnit P h

/-! ## Characteristic ideal of single-factor profiles -/

/-- The characteristic ideal of a single `Λ/(p^n)` summand. -/
theorem charIdeal_singlePPower (n : ℕ) :
    charIdeal (singlePPowerProfile (p := p) n) =
      Ideal.span ({primeInLambda p ^ n} : Set (Lambda ℤ_[p])) := by
  rw [charIdeal, LambdaElementaryProfile.characteristicIdeal,
    singlePPowerProfile_characteristicElement]

/-- The characteristic ideal of a single `Λ/(D)` distinguished summand. -/
theorem charIdeal_singleDistinguished (D : DistinguishedPolynomial p) :
    charIdeal (singleDistinguishedProfile D) =
      Ideal.span ({D.toPowerSeries} : Set (Lambda ℤ_[p])) := by
  rw [charIdeal, LambdaElementaryProfile.characteristicIdeal,
    singleDistinguishedProfile_characteristicElement]

/-! ## μ and λ from the characteristic element -/

/-- The μ exponent appears as the `p`-adic valuation power in the characteristic element. -/
theorem charElem_mu_factor (P : LambdaElementaryProfile p) :
    charElem P = primeInLambda p ^ P.mu *
      Finset.univ.prod (fun i => (P.distinguishedFactor i).toPowerSeries) :=
  rfl

/-- Appending two profiles sums their μ invariants, reflected in the characteristic element. -/
theorem charElem_append_mu (P Q : LambdaElementaryProfile p) :
    (P.append Q).mu = P.mu + Q.mu :=
  append_mu P Q

/-- Appending two profiles sums their λ invariants. -/
theorem charElem_append_lambda (P Q : LambdaElementaryProfile p) :
    (P.append Q).lambda = P.lambda + Q.lambda :=
  append_lambda P Q

/-! ## Monotonicity / ideal containment -/

/-- If two profiles satisfy `charElem P ∣ charElem Q` then `charIdeal Q ≤ charIdeal P`. -/
theorem charIdeal_le_of_dvd (P Q : LambdaElementaryProfile p)
    (h : charElem P ∣ charElem Q) : charIdeal Q ≤ charIdeal P := by
  rw [charIdeal, charIdeal, LambdaElementaryProfile.characteristicIdeal,
    LambdaElementaryProfile.characteristicIdeal]
  apply Ideal.span_singleton_le_span_singleton.mpr h

/-- The characteristic ideal is contained in the μ-only part of the decomposition. -/
theorem charIdeal_le_pPower_span (P : LambdaElementaryProfile p) :
    charIdeal P ≤ Ideal.span ({primeInLambda p ^ P.mu} : Set (Lambda ℤ_[p])) := by
  rw [charIdeal, LambdaElementaryProfile.characteristicIdeal]
  apply Ideal.span_singleton_le_span_singleton.mpr
  exact ⟨Finset.univ.prod (fun i => (P.distinguishedFactor i).toPowerSeries),
    charElem_mu_factor P⟩

/-! ## Gap wall: uniqueness requires the structure theorem axiom

The profile-level characteristic ideal is well-defined given a specific profile
decomposition.  Proving that two pseudo-isomorphic modules have the same
characteristic ideal (independence of the choice of elementary model) requires
the full Iwasawa structure theorem.

This API is not available at the profile level and is flagged below.
See `StructureTheorem.lean` for the module-level `characteristicIdeal` derived
from `iwasawaStructureTheorem`. -/

/-- Gap wall: characteristic ideal uniqueness (independence of elementary model)
is not provable without `iwasawaStructureTheorem`. -/
def HasCharacteristicIdealUniquenessAPI (p : ℕ) [Fact p.Prime] : Prop := False

/-- Gap wall: the characteristic ideal functor (pseudo-isomorphism → ideal containment)
is not available without the structure theorem. -/
def HasCharacteristicIdealFunctorAPI (p : ℕ) [Fact p.Prime] : Prop := False

end Iwasawa
end Roots
end MathlibExpansion
