import MathlibExpansion.Roots.Iwasawa.Pseudo
import MathlibExpansion.Roots.Iwasawa.Distinguished
import Mathlib.RingTheory.Finiteness.Basic

/-!
# Iwasawa Elementary: LambdaElementaryProfile over ℤ_p

Defines `LambdaElementaryProfile p` — the data of an elementary Iwasawa
decomposition.  Key fixes over the deprecated `IwasawaStructure.lean`:

**Blindspot A fix**: no `primeElement` field.  The prime is always `p ∈ ℤ_p`,
injected via `primeInLambda p`.  No unconstrained `Lambda R` field that could
be set to anything.

**Blindspot B fix** (via `DistinguishedPolynomial`): `distinguishedFactor`
fields carry `DistinguishedPolynomial p` values that enforce `degree_pos`.
No spurious degree-0 factors.

**Honest λ**: `distinguishedDegree i := (distinguishedFactor i).poly.natDegree`
and `lambda := ∑ distinguishedDegree`.  These are real, not hardcoded to 0.

**No `IsDistinguished := True`**: that type has been deleted.  Distinguished
polynomials are governed by `DistinguishedPolynomial` (see Distinguished.lean).

**No `lambda_eq_zero_of_placeholder_degree`**: deleted.  The correct theorem is
`singleDistinguishedProfile_lambda D : lambda = D.poly.natDegree`.

**Clean `append`**: no `hprime` hypothesis because `primeElement` is gone.
-/

namespace MathlibExpansion
namespace Roots
namespace Iwasawa

open scoped Padic

/-- The image of the rational prime `p` in the Iwasawa algebra `Λ = ℤ_p[[T]]`.
This is the constant power series equal to `(p : ℤ_p)`. -/
noncomputable def primeInLambda (p : ℕ) [Fact p.Prime] : Lambda ℤ_[p] :=
  PowerSeries.C ℤ_[p] (p : ℤ_[p])

/-- An elementary Iwasawa profile over `ℤ_p`.

No `primeElement` field: the prime is always `primeInLambda p` (Blindspot A fix).
`distinguishedFactor` carries `DistinguishedPolynomial p` values (Blindspot B fix). -/
structure LambdaElementaryProfile (p : ℕ) [Fact p.Prime] where
  rank : ℕ
  pPowerIndex : Type
  [pPowerFintype : Fintype pPowerIndex]
  pPowerExponent : pPowerIndex → ℕ
  distinguishedIndex : Type
  [distinguishedFintype : Fintype distinguishedIndex]
  distinguishedFactor : distinguishedIndex → DistinguishedPolynomial p

attribute [instance] LambdaElementaryProfile.pPowerFintype
attribute [instance] LambdaElementaryProfile.distinguishedFintype

namespace LambdaElementaryProfile

variable {p : ℕ} [Fact p.Prime]

/-- The Iwasawa μ invariant: total exponent in the `p`-power torsion part. -/
def mu (P : LambdaElementaryProfile p) : ℕ :=
  Finset.univ.sum P.pPowerExponent

/-- The degree of the `j`-th distinguished factor.  **Real**, not a placeholder. -/
def distinguishedDegree (P : LambdaElementaryProfile p) (i : P.distinguishedIndex) : ℕ :=
  (P.distinguishedFactor i).poly.natDegree

/-- The Iwasawa λ invariant: sum of degrees of all distinguished factors.
**Real** sum of actual polynomial degrees. -/
def lambda (P : LambdaElementaryProfile p) : ℕ :=
  Finset.univ.sum (P.distinguishedDegree ·)

/-- The profile-level characteristic element `p^μ · ∏_j D_j`. -/
noncomputable def characteristicElement (P : LambdaElementaryProfile p) : Lambda ℤ_[p] :=
  primeInLambda p ^ P.mu *
    Finset.univ.prod (fun i => (P.distinguishedFactor i).toPowerSeries)

/-- The principal ideal generated by the characteristic element. -/
noncomputable def characteristicIdeal (P : LambdaElementaryProfile p) : Ideal (Lambda ℤ_[p]) :=
  Ideal.span ({P.characteristicElement} : Set (Lambda ℤ_[p]))

/-! ## Single-factor profiles -/

/-- The elementary profile consisting of one `Λ/(p^n)` summand. -/
def singlePPowerProfile (n : ℕ) : LambdaElementaryProfile p where
  rank := 0
  pPowerIndex := PUnit
  pPowerExponent := fun _ => n
  distinguishedIndex := PEmpty
  distinguishedFactor := PEmpty.elim

@[simp] theorem singlePPowerProfile_mu (n : ℕ) :
    (singlePPowerProfile (p := p) n).mu = n := by
  simp [singlePPowerProfile, mu]

@[simp] theorem singlePPowerProfile_lambda (n : ℕ) :
    (singlePPowerProfile (p := p) n).lambda = 0 := by
  simp [singlePPowerProfile, lambda, distinguishedDegree]

@[simp] theorem singlePPowerProfile_characteristicElement (n : ℕ) :
    (singlePPowerProfile (p := p) n).characteristicElement = primeInLambda p ^ n := by
  rw [characteristicElement, singlePPowerProfile_mu]
  simp [singlePPowerProfile]

/-- The elementary profile consisting of one `Λ/(D)` distinguished summand. -/
def singleDistinguishedProfile (D : DistinguishedPolynomial p) : LambdaElementaryProfile p where
  rank := 0
  pPowerIndex := PEmpty
  pPowerExponent := PEmpty.elim
  distinguishedIndex := PUnit
  distinguishedFactor := fun _ => D

@[simp] theorem singleDistinguishedProfile_mu (D : DistinguishedPolynomial p) :
    (singleDistinguishedProfile D).mu = 0 := by
  simp [singleDistinguishedProfile, mu]

/-- The λ invariant of a single distinguished factor equals its polynomial degree.
This is the **honest** theorem replacing the deprecated
`singleDistinguishedProfile_lambda_placeholder` which returned 0. -/
@[simp] theorem singleDistinguishedProfile_lambda (D : DistinguishedPolynomial p) :
    (singleDistinguishedProfile D).lambda = D.poly.natDegree := by
  simp [singleDistinguishedProfile, lambda, distinguishedDegree]

@[simp] theorem singleDistinguishedProfile_characteristicElement (D : DistinguishedPolynomial p) :
    (singleDistinguishedProfile D).characteristicElement = D.toPowerSeries := by
  simp [singleDistinguishedProfile, characteristicElement, mu,
    DistinguishedPolynomial.toPowerSeries]

/-! ## Profile concatenation (append) -/

/-- Concatenate two elementary profiles.
No `hprime` hypothesis needed since the prime is always `p`. -/
noncomputable def append (P Q : LambdaElementaryProfile p) : LambdaElementaryProfile p where
  rank := P.rank + Q.rank
  pPowerIndex := Sum P.pPowerIndex Q.pPowerIndex
  pPowerExponent := Sum.elim P.pPowerExponent Q.pPowerExponent
  distinguishedIndex := Sum P.distinguishedIndex Q.distinguishedIndex
  distinguishedFactor := Sum.elim P.distinguishedFactor Q.distinguishedFactor

@[simp] theorem append_rank (P Q : LambdaElementaryProfile p) :
    (P.append Q).rank = P.rank + Q.rank := rfl

@[simp] theorem append_mu (P Q : LambdaElementaryProfile p) :
    (P.append Q).mu = P.mu + Q.mu := by
  simp [append, mu, Finset.sum_sumElim]

@[simp] theorem append_lambda (P Q : LambdaElementaryProfile p) :
    (P.append Q).lambda = P.lambda + Q.lambda := by
  simp [append, lambda, distinguishedDegree, Finset.sum_sumElim]

/-- Characteristic element multiplies under append.
No `hprime` hypothesis — a direct consequence of removing the `primeElement` field. -/
@[simp] theorem append_characteristicElement (P Q : LambdaElementaryProfile p) :
    (P.append Q).characteristicElement = P.characteristicElement * Q.characteristicElement := by
  simp [append, characteristicElement, mu, pow_add, mul_assoc, mul_left_comm, mul_comm,
    Finset.prod_sumElim]

theorem append_characteristicIdeal_generator (P Q : LambdaElementaryProfile p) :
    (P.append Q).characteristicIdeal =
      Ideal.span
        ({P.characteristicElement * Q.characteristicElement} : Set (Lambda ℤ_[p])) := by
  rw [characteristicIdeal, append_characteristicElement]

theorem mu_eq_zero_of_pPowerExponent_eq_zero (P : LambdaElementaryProfile p)
    (h : ∀ i, P.pPowerExponent i = 0) : P.mu = 0 := by
  simp [mu, h]

theorem characteristicIdeal_eq_top_of_isUnit (P : LambdaElementaryProfile p)
    (hP : IsUnit P.characteristicElement) : P.characteristicIdeal = ⊤ := by
  rw [characteristicIdeal, Ideal.eq_top_iff_one]
  have hmem : P.characteristicElement ∈
      Ideal.span ({P.characteristicElement} : Set (Lambda ℤ_[p])) :=
    Ideal.subset_span (by simp)
  rcases hP with ⟨u, hu⟩
  have hunit_mem : ((↑u⁻¹ : Lambda ℤ_[p]) * P.characteristicElement) ∈
      Ideal.span ({P.characteristicElement} : Set (Lambda ℤ_[p])) :=
    Ideal.mul_mem_left _ _ hmem
  have hone : ((↑u⁻¹ : Lambda ℤ_[p]) * P.characteristicElement) = 1 := by
    rw [← hu]; exact Units.inv_mul u
  simpa [hone] using hunit_mem

end LambdaElementaryProfile

/-! ## Free profile -/

noncomputable def freeLambdaElementaryProfile (p : ℕ) [Fact p.Prime]
    (rank : ℕ) : LambdaElementaryProfile p where
  rank := rank
  pPowerIndex := PEmpty
  pPowerExponent := PEmpty.elim
  distinguishedIndex := PEmpty
  distinguishedFactor := PEmpty.elim

@[simp] theorem freeLambdaElementaryProfile_mu (p : ℕ) [Fact p.Prime] (rank : ℕ) :
    (freeLambdaElementaryProfile p rank).mu = 0 := by
  simp [freeLambdaElementaryProfile, LambdaElementaryProfile.mu]

@[simp] theorem freeLambdaElementaryProfile_lambda (p : ℕ) [Fact p.Prime] (rank : ℕ) :
    (freeLambdaElementaryProfile p rank).lambda = 0 := by
  simp [freeLambdaElementaryProfile, LambdaElementaryProfile.lambda,
    LambdaElementaryProfile.distinguishedDegree]

/-! ## Concrete profile carrier and realizations -/

/-- The concrete Λ-module attached to a profile:
`Λ^rank × (∏_i Λ/(p^{n_i})) × (∏_j Λ/(D_j))` -/
abbrev concreteProfileCarrier {p : ℕ} [Fact p.Prime]
    (P : LambdaElementaryProfile p) : Type :=
  (Fin P.rank → Lambda ℤ_[p]) ×
    (∀ i : P.pPowerIndex, pPowerElementary ℤ_[p] (primeInLambda p) (P.pPowerExponent i)) ×
      (∀ j : P.distinguishedIndex,
        cyclicQuotient ℤ_[p] (P.distinguishedFactor j).toPowerSeries)

theorem concreteProfileCarrier_module_finite {p : ℕ} [Fact p.Prime]
    (P : LambdaElementaryProfile p) :
    Module.Finite (Lambda ℤ_[p]) (concreteProfileCarrier P) := by
  infer_instance

/-- A module that realizes a profile over ℤ_p. -/
structure ProfileRealization (p : ℕ) [Fact p.Prime] (P : LambdaElementaryProfile p) where
  carrier : Type*
  [addCommGroup : AddCommGroup carrier]
  [module : Module (Lambda ℤ_[p]) carrier]
  finite : Module.Finite (Lambda ℤ_[p]) carrier

attribute [instance] ProfileRealization.addCommGroup
attribute [instance] ProfileRealization.module

namespace ProfileRealization

variable {p : ℕ} [Fact p.Prime]

instance (P : LambdaElementaryProfile p) (E : ProfileRealization p P) :
    Module.Finite (Lambda ℤ_[p]) E.carrier := E.finite

def toFinitelyGeneratedLambdaModule {P : LambdaElementaryProfile p}
    (E : ProfileRealization p P) : FinitelyGeneratedLambdaModule ℤ_[p] where
  carrier := E.carrier
  finite := E.finite

end ProfileRealization

/-- The canonical concrete realization of a profile. -/
noncomputable def concreteProfileRealization {p : ℕ} [Fact p.Prime]
    (P : LambdaElementaryProfile p) : ProfileRealization p P where
  carrier := concreteProfileCarrier P
  finite := inferInstance

/-- The concrete carrier of the free elementary profile is linearly equivalent
to the expected free module. -/
noncomputable def freeProfileConcreteEquiv {p : ℕ} [Fact p.Prime] (rank : ℕ) :
    (Fin rank → Lambda ℤ_[p]) ≃ₗ[Lambda ℤ_[p]]
      concreteProfileCarrier (freeLambdaElementaryProfile p rank) where
  toFun x := (x, (fun i => PEmpty.elim i), fun j => PEmpty.elim j)
  invFun y := y.1
  left_inv x := rfl
  right_inv := by
    rintro ⟨x, hp, hd⟩
    simp [concreteProfileCarrier, freeLambdaElementaryProfile]
    constructor <;> funext i <;> cases i
  map_add' x y := by
    simp [concreteProfileCarrier, freeLambdaElementaryProfile]
    constructor <;> funext i <;> cases i
  map_smul' a x := by
    simp [concreteProfileCarrier, freeLambdaElementaryProfile]
    constructor <;> funext i <;> cases i

/-- A full elementary profile decomposition of a f.g. Λ-module:
profile data + a realization + a pseudo-isomorphism.  The `concretePseudo`
field ties the legacy arbitrary realization layer back to the concrete
elementary module attached to the profile, which is the surface needed for
uniqueness of elementary factors. -/
structure LambdaProfileDecomposition (p : ℕ) [Fact p.Prime]
    (M : FinitelyGeneratedLambdaModule ℤ_[p]) where
  profile : LambdaElementaryProfile p
  realization : ProfileRealization p profile
  pseudo : Nonempty (PseudoIsomorphism (R := ℤ_[p]) M.carrier realization.carrier)
  concretePseudo :
    Nonempty (PseudoIsomorphism (R := ℤ_[p]) M.carrier (concreteProfileCarrier profile))

namespace LambdaProfileDecomposition

variable {p : ℕ} [Fact p.Prime] {M : FinitelyGeneratedLambdaModule ℤ_[p]}

noncomputable def characteristicIdeal (D : LambdaProfileDecomposition p M) :
    Ideal (Lambda ℤ_[p]) :=
  D.profile.characteristicIdeal

def mu (D : LambdaProfileDecomposition p M) : ℕ := D.profile.mu

def lambda (D : LambdaProfileDecomposition p M) : ℕ := D.profile.lambda

@[simp] theorem characteristicIdeal_eq_profile (D : LambdaProfileDecomposition p M) :
    D.characteristicIdeal = D.profile.characteristicIdeal := rfl

end LambdaProfileDecomposition

/-- Missing API: constructing an elementary profile from an arbitrary f.g. Λ-module. -/
def HasLambdaProfileDecompositionAPI (p : ℕ) [Fact p.Prime] : Prop := False

/-- Missing API: uniqueness of the characteristic ideal. -/
def HasLambdaCharacteristicIdealAPI (p : ℕ) [Fact p.Prime] : Prop := False

/-- Honest wall: both APIs are currently missing. -/
def HasFullIwasawaAlgebraAPI (p : ℕ) [Fact p.Prime] : Prop :=
  HasLambdaProfileDecompositionAPI p ∧ HasLambdaCharacteristicIdealAPI p

end Iwasawa
end Roots
end MathlibExpansion
