import MathlibExpansion.LieGroups.Chevalley.AnalyticManifold

/-!
# Left-invariant vector fields

This file exposes Mathlib's `LeftInvariantDerivation` surface under the
Chevalley campaign namespace.
-/

noncomputable section

open scoped Manifold

namespace MathlibExpansion.LieGroups.Chevalley

abbrev AnalyticLeftInvariantVectorField
    {𝕜 : Type*} [NontriviallyNormedField 𝕜]
    {H : Type*} [TopologicalSpace H]
    {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    (I : ModelWithCorners 𝕜 E H) (G : Type*)
    [TopologicalSpace G] [ChartedSpace H G] [Monoid G] [ContMDiffMul I ⊤ G] : Type _ :=
  LeftInvariantDerivation I G

section

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
variable {H : Type*} [TopologicalSpace H]
variable {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
variable {I : ModelWithCorners 𝕜 E H}
variable {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Monoid G] [ContMDiffMul I ⊤ G]

/-- Evaluation at the identity is the textbook tangent-at-identity probe. -/
abbrev evalAtOne :
    LeftInvariantDerivation I G →ₗ[𝕜] PointDerivation I (1 : G) :=
  LeftInvariantDerivation.evalAt (I := I) (g := (1 : G))

/-- Left invariance transports the value at `1` to the value at any `g`. -/
theorem leftInvariant_evalAt (X : LeftInvariantDerivation I G) (g : G) :
    𝒅ₕ (smoothLeftMul_one I g) (evalAtOne (I := I) X) =
      LeftInvariantDerivation.evalAt g X := by
  simpa [evalAtOne] using X.left_invariant (I := I) (g := g)

/-- Evaluation is compatible with multiplication in the group variable. -/
theorem evalAt_mul (X : LeftInvariantDerivation I G) (g h : G) :
    LeftInvariantDerivation.evalAt (g * h) X =
      𝒅ₕ (L_apply I g h) (LeftInvariantDerivation.evalAt h X) := by
  simpa using LeftInvariantDerivation.evalAt_mul (I := I) (g := g) (h := h) (X := X)

end

section GeneralLinear

variable {𝕜 : Type*} [RCLike 𝕜]
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace 𝕜 V] [CompleteSpace V]

/--
The left-invariant vector field generated by `X` on the concrete model `GL(V)`, written in the
singleton chart `GL(V) ↪ V →L[𝕜] V`.
-/
def generalLinearLeftInvariantField (X : V →L[𝕜] V) :
    GeneralLinearGroup (𝕜 := 𝕜) (V := V) → V →L[𝕜] V :=
  fun g => (g : V →L[𝕜] V) * X

@[simp] theorem generalLinearLeftInvariantField_one (X : V →L[𝕜] V) :
    generalLinearLeftInvariantField (𝕜 := 𝕜) (V := V) X 1 = X := by
  simp [generalLinearLeftInvariantField]

theorem generalLinearLeftInvariantField_mul (X : V →L[𝕜] V)
    (g h : GeneralLinearGroup (𝕜 := 𝕜) (V := V)) :
    generalLinearLeftInvariantField (𝕜 := 𝕜) (V := V) X (g * h) =
      (g : V →L[𝕜] V) * generalLinearLeftInvariantField (𝕜 := 𝕜) (V := V) X h := by
  simp [generalLinearLeftInvariantField, mul_assoc]

theorem contMDiff_generalLinearLeftInvariantField (X : V →L[𝕜] V) :
    ContMDiff 𝓘(𝕜, V →L[𝕜] V) 𝓘(𝕜, V →L[𝕜] V) ω
      (generalLinearLeftInvariantField (𝕜 := 𝕜) (V := V) X) := by
  let compRightX : (V →L[𝕜] V) →L[𝕜] (V →L[𝕜] V) :=
    (ContinuousLinearMap.isBoundedLinearMap_comp_right
      (𝕜 := 𝕜) (E := V) (F := V) (G := V) X).toContinuousLinearMap
  simpa [compRightX, generalLinearLeftInvariantField] using
    (ContinuousLinearMap.contMDiff compRightX).comp
      (Units.contMDiff_val (𝕜 := 𝕜) (R := V →L[𝕜] V) (n := ω))

end GeneralLinear

end MathlibExpansion.LieGroups.Chevalley
