import Mathlib

/-!
# One-parameter subgroups

This file formalizes the Banach-algebra one-parameter subgroup generated by a
single element via the exponential map.
-/

noncomputable section

namespace MathlibExpansion.LieGroups.Chevalley

open scoped BigOperators

section

variable {𝕜 : Type*} [RCLike 𝕜]
variable {A : Type*} [NormedRing A] [NormedAlgebra 𝕜 A] [CompleteSpace A]

/-- Chevalley's one-parameter subgroup carrier in the concrete Banach-algebra model. -/
abbrev OneParameterSubgroup := ContinuousMonoidHom (Multiplicative 𝕜) Aˣ

/-- The exponential line generated by `x`, valued in the unit group. -/
def oneParameterSubgroup (x : A) (t : 𝕜) : Aˣ :=
  (NormedSpace.isUnit_exp 𝕜 (t • x)).unit

@[simp] theorem coe_oneParameterSubgroup (x : A) (t : 𝕜) :
    ((oneParameterSubgroup (𝕜 := 𝕜) x t : Aˣ) : A) = NormedSpace.exp 𝕜 (t • x) :=
  IsUnit.unit_spec _

@[simp] theorem oneParameterSubgroup_zero (x : A) :
    oneParameterSubgroup (𝕜 := 𝕜) x 0 = 1 := by
  ext
  simp [oneParameterSubgroup]

@[simp] theorem oneParameterSubgroup_inv (x : A) (t : 𝕜) :
    (oneParameterSubgroup (𝕜 := 𝕜) x t)⁻¹ =
      oneParameterSubgroup (𝕜 := 𝕜) (-x) t := by
  apply inv_eq_of_mul_eq_one_right
  ext
  have hcomm : Commute (t • x) (t • (-x)) := by
    simpa [neg_smul] using (Commute.refl (t • x)).neg_right
  calc
    NormedSpace.exp 𝕜 (t • x) * NormedSpace.exp 𝕜 (t • (-x))
        = NormedSpace.exp 𝕜 (t • x + t • (-x)) := by
            symm
            exact NormedSpace.exp_add_of_commute (𝕂 := 𝕜) (x := t • x) (y := t • (-x)) hcomm
    _ = 1 := by simp [neg_smul]

@[simp] theorem oneParameterSubgroup_add (x : A) (s t : 𝕜) :
    oneParameterSubgroup (𝕜 := 𝕜) x (s + t) =
      oneParameterSubgroup (𝕜 := 𝕜) x s * oneParameterSubgroup (𝕜 := 𝕜) x t := by
  have hcomm : Commute (s • x) (t • x) := by
    exact (Commute.refl x).smul_left s |>.smul_right t
  ext
  simpa [oneParameterSubgroup, add_smul] using
    (NormedSpace.exp_add_of_commute (𝕂 := 𝕜) (x := s • x) (y := t • x) hcomm)

theorem analyticAt_oneParameterSubgroup_val (x : A) (t : 𝕜) :
    AnalyticAt 𝕜
      (fun s : 𝕜 => ((oneParameterSubgroup (𝕜 := 𝕜) x s : Aˣ) : A)) t := by
  have hsmul : AnalyticAt 𝕜 (fun s : 𝕜 => s • x) t := by
    exact
      (analyticAt_id : AnalyticAt 𝕜 (fun s : 𝕜 => s) t).smul
        (analyticAt_const : AnalyticAt 𝕜 (fun _ : 𝕜 => x) t)
  have hexp : AnalyticAt 𝕜 (fun y : A => NormedSpace.exp 𝕜 y) (t • x) := by
    simpa using NormedSpace.exp_analytic (𝕂 := 𝕜) (𝔸 := A) (x := t • x)
  simpa [oneParameterSubgroup] using hexp.comp_of_eq' hsmul rfl

theorem hasDerivAt_oneParameterSubgroup_val (x : A) (t : 𝕜) :
    HasDerivAt
      (fun s : 𝕜 => ((oneParameterSubgroup (𝕜 := 𝕜) x s : Aˣ) : A))
      (NormedSpace.exp 𝕜 (t • x) * x) t := by
  simpa [oneParameterSubgroup] using
    (hasDerivAt_exp_smul_const (𝕂 := 𝕜) (𝔸 := A) x t)

@[simp] theorem hasDerivAt_oneParameterSubgroup_val_zero (x : A) :
    HasDerivAt
      (fun s : 𝕜 => ((oneParameterSubgroup (𝕜 := 𝕜) x s : Aˣ) : A))
      x 0 := by
  simpa using hasDerivAt_oneParameterSubgroup_val (𝕜 := 𝕜) (x := x) (t := 0)

/-- The Banach-algebra exponential line bundled as a continuous one-parameter subgroup. -/
def oneParameterSubgroupHom (x : A) : OneParameterSubgroup (𝕜 := 𝕜) (A := A) where
  toFun t := oneParameterSubgroup (𝕜 := 𝕜) x (Multiplicative.toAdd t)
  map_one' := oneParameterSubgroup_zero (𝕜 := 𝕜) x
  map_mul' s t := by
    simpa using
      oneParameterSubgroup_add (𝕜 := 𝕜) x (Multiplicative.toAdd s) (Multiplicative.toAdd t)
  continuous_toFun := by
    refine Units.continuous_iff.2 ?_
    constructor
    · refine continuous_iff_continuousAt.2 ?_
      intro t
      simpa using
        (analyticAt_oneParameterSubgroup_val (𝕜 := 𝕜) (x := x) (t := Multiplicative.toAdd t)).continuousAt
    · refine continuous_iff_continuousAt.2 ?_
      intro t
      simpa [oneParameterSubgroup_inv] using
        (analyticAt_oneParameterSubgroup_val (𝕜 := 𝕜) (x := -x) (t := Multiplicative.toAdd t)).continuousAt

@[simp] theorem oneParameterSubgroupHom_apply (x : A) (t : 𝕜) :
    oneParameterSubgroupHom (𝕜 := 𝕜) x (Multiplicative.ofAdd t) =
      oneParameterSubgroup (𝕜 := 𝕜) x t :=
  rfl

end

end MathlibExpansion.LieGroups.Chevalley
