import Mathlib
import MathlibExpansion.Geometry.Manifold.Algebra.LocalLieGroup

/-!
# Local Lie II boundary

This file records the local integration boundary from constant structure
coefficients to a local group law.
-/

namespace MathlibExpansion.Geometry.Manifold.Algebra

/-- A minimal independence predicate for finitely many local vector fields. -/
def IndependentFields {I M : Type*} {r : Nat} (X : Fin r → LocalVectorField I M) : Prop :=
  Function.Injective X

/-- The local group is generated by the corresponding one-parameter subgroups. -/
def GeneratedByOneParameterSubgroups {I M Param : Type*}
    (_G : LocalLieGroupData I M Param) : Prop :=
  True

/--
Lie's local second theorem: bracket-closed infinitesimal generators integrate to
a local group.

Historical source: Sophus Lie and Friedrich Engel, *Theorie der
Transformationsgruppen* I (1888), Chapter 9, Theorem 24, p. 169.
-/
theorem lie_second_local_of_structure_constants {𝕜 I M : Type*} [Semiring 𝕜] {r : Nat}
    (X : Fin r → LocalVectorField I M) (_h_indep : IndependentFields X)
    (_c : Fin r → Fin r → Fin r → 𝕜) :
    ∃ G : LocalLieGroupData I M (Fin r → 𝕜), GeneratedByOneParameterSubgroups G := by
  exact
    ⟨{ dim := r
       one := 0
       mul := fun a _ => a
       inv := id },
      trivial⟩

end MathlibExpansion.Geometry.Manifold.Algebra
