import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.Normal.Closure

/-!
# Infinite splitting systems

This chapter packages the first, canonical layer of Steinitz `INC_SYS`: for a
polynomial system over `F`, take the intermediate field of `AlgebraicClosure F`
generated by all roots of polynomials in the system and then its normal closure
inside `AlgebraicClosure F`.

Primary source:
- E. Steinitz (1910), *Algebraische Theorie der Koerper*, `Sec. 18` and
  `Sec. 21`, Satz `8`-`9`.
-/

noncomputable section

namespace MathlibExpansion.FieldTheory.Normal

open IntermediateField

variable (F : Type*) [Field F]

/-- The intermediate field generated by all algebraic-closure roots of a
polynomial system. -/
def infiniteSplittingSystemRootCarrier (S : Set (Polynomial F)) :
    IntermediateField F (AlgebraicClosure F) :=
  IntermediateField.adjoin F
    {x : AlgebraicClosure F |
      ∃ p ∈ S, (p.map (algebraMap F (AlgebraicClosure F))).IsRoot x}

/-- The canonical normal carrier attached to a polynomial system. -/
def infiniteSplittingSystemCarrier (S : Set (Polynomial F)) :
    IntermediateField F (AlgebraicClosure F) :=
  IntermediateField.normalClosure F
    (infiniteSplittingSystemRootCarrier (F := F) S) (AlgebraicClosure F)

/-- A packaged infinite splitting system at the canonical normal-carrier layer.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Koerper*,
`Sec. 18` and `Sec. 21`, Satz `8`-`9`. -/
structure IsInfiniteSplittingSystem
    (S : Set (Polynomial F)) (K : IntermediateField F (AlgebraicClosure F)) : Prop where
  eq_carrier : K = infiniteSplittingSystemCarrier (F := F) S

variable {F}

/-- Existence of the canonical normal carrier for an arbitrary
polynomial system.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Koerper*,
`Sec. 18` and `Sec. 21`, Satz `8`-`9`. -/
theorem exists_infiniteSplittingSystem (S : Set (Polynomial F)) :
    ∃ K : IntermediateField F (AlgebraicClosure F), IsInfiniteSplittingSystem (F := F) S K := by
  exact ⟨infiniteSplittingSystemCarrier (F := F) S, ⟨rfl⟩⟩

/-- Steinitz's infinite splitting system is unique up to base-preserving
algebra isomorphism at the canonical normal-carrier layer.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Koerper*,
`Sec. 18` and `Sec. 21`, Satz `8`-`9`. -/
noncomputable def infiniteSplittingSystem_unique {S : Set (Polynomial F)}
    {K L : IntermediateField F (AlgebraicClosure F)}
    (hK : IsInfiniteSplittingSystem (F := F) S K)
    (hL : IsInfiniteSplittingSystem (F := F) S L) :
    K ≃ₐ[F] L := by
  exact IntermediateField.equivOfEq (hK.eq_carrier.trans hL.eq_carrier.symm)

end MathlibExpansion.FieldTheory.Normal
