import Mathlib.FieldTheory.Normal.Closure
import Mathlib.FieldTheory.PrimitiveElement

/-!
# Primitive-generator normal closure facade

This chapter packages Steinitz `NSC_08`. The primitive element theorem and the
normal-closure-by-root-set theorem are both upstream, but Mathlib does not
export the single textbook sentence combining them.

We keep that sentence as a narrow boundary in the sibling library.

Primary source:
- E. Steinitz (1910), *Algebraische Theorie der Koerper*, `Sec. 8` and
  `Sec. 21`.
-/

noncomputable section

namespace MathlibExpansion.FieldTheory.Normal

open IntermediateField Polynomial

variable {F K L : Type*} [Field F] [Field K] [Field L]
variable [Algebra F K] [Algebra F L] [FiniteDimensional F K] [Algebra.IsSeparable F K]
variable [Algebra K L] [IsScalarTower F K L] [Normal F L]

/-- For a finite separable extension, the normal closure is generated by the
roots of the minimal polynomial of a primitive generator. -/
theorem normalClosure_eq_adjoin_rootSet_of_primitive :
    ∃ α : K,
      IntermediateField.adjoin F ({α} : Set K) = ⊤ ∧
      normalClosure F K L = IntermediateField.adjoin F ((minpoly F α).rootSet L) := by
  classical
  obtain ⟨α, hα⟩ := Field.exists_primitive_element F K
  refine ⟨α, hα, ?_⟩
  apply le_antisymm
  · rw [normalClosure_def]
    refine iSup_le fun f => ?_
    calc
      f.fieldRange = (F⟮α⟯ : IntermediateField F K).map f := by
        rw [hα, AlgHom.fieldRange_eq_map]
      _ = IntermediateField.adjoin F (f '' ({α} : Set K)) := by
        rw [IntermediateField.adjoin_map]
      _ ≤ IntermediateField.adjoin F ((minpoly F α).rootSet L) := by
        rw [IntermediateField.adjoin_le_iff]
        rintro y ⟨x, hx, rfl⟩
        rw [Set.mem_singleton_iff] at hx
        subst x
        exact IntermediateField.subset_adjoin F _ <| by
          rw [mem_rootSet_of_ne (minpoly.ne_zero (Algebra.IsIntegral.isIntegral α))]
          rw [Polynomial.aeval_algHom_apply f α (minpoly F α), minpoly.aeval, map_zero]
  · rw [IntermediateField.adjoin_le_iff]
    intro y hy
    have hsplits : ∀ x : K, (minpoly F x).Splits (algebraMap F L) := by
      intro x
      let f : K →ₐ[F] L := IsScalarTower.toAlgHom F K L
      have hmin : minpoly F (f x) = minpoly F x := minpoly.algHom_eq f f.injective x
      exact hmin ▸ (inferInstanceAs (Normal F L)).splits (f x)
    have hyzero : aeval y (minpoly F α) = 0 :=
      (mem_rootSet_of_ne (minpoly.ne_zero (Algebra.IsIntegral.isIntegral α))).mp hy
    obtain ⟨f, hf⟩ := IntermediateField.exists_algHom_of_splits_of_aeval
      (F := F) (E := K) (K := L) (x := α) (y := y)
      (fun x => ⟨Algebra.IsIntegral.isIntegral x, hsplits x⟩) hyzero
    exact (AlgHom.fieldRange_le_normalClosure (F := F) (K := K) (L := L) f) ⟨α, hf⟩

end MathlibExpansion.FieldTheory.Normal
