import MathlibExpansion.Foundations.Dedekind.SimplyInfinite

/-!
# Dedekind chains

This file packages the basic tail-chain API induced by a simply infinite system.
-/

namespace MathlibExpansion
namespace Foundations
namespace Dedekind

open Set

namespace SimplyInfiniteSystem

variable {α : Type*} (S : SimplyInfiniteSystem α)

/-- The number-chain generated by `a` consists of all later elements in the canonical enumeration. -/
def numChain (a : α) : Set α := {b | S.equivNat a ≤ S.equivNat b}

@[simp] theorem mem_numChain_iff {a b : α} :
    b ∈ S.numChain a ↔ S.equivNat a ≤ S.equivNat b := Iff.rfl

theorem succ_numChain_eq_tail (a : α) :
    S.numChain (S.succ a) = {b | b ∈ S.numChain a ∧ b ≠ a} := by
  ext b
  constructor
  · intro hb
    have hb' : S.equivNat a + 1 ≤ S.equivNat b := by
      simpa [SimplyInfiniteSystem.numChain, S.equivNat_succ] using hb
    refine ⟨?_, ?_⟩
    · exact Nat.le_of_succ_le hb'
    · intro hba
      have : S.equivNat a + 1 ≤ S.equivNat a := by simpa [hba] using hb'
      exact Nat.not_succ_le_self _ this
  · rintro ⟨hb, hba⟩
    have hne : S.equivNat a ≠ S.equivNat b := by
      intro hEq
      exact hba (S.equivNat.injective hEq).symm
    simpa [SimplyInfiniteSystem.numChain, S.equivNat_succ] using
      Nat.succ_le_of_lt (lt_of_le_of_ne hb hne)

theorem numChain_eq_insert_succChain (a : α) :
    S.numChain a = insert a (S.numChain (S.succ a)) := by
  ext b
  constructor
  · intro hb
    have hb' : S.equivNat a ≤ S.equivNat b := by simpa [SimplyInfiniteSystem.numChain] using hb
    rcases eq_or_lt_of_le hb' with hEq | hlt
    · exact Or.inl (S.equivNat.injective hEq.symm)
    · exact Or.inr (by
        simpa [SimplyInfiniteSystem.numChain, S.equivNat_succ] using Nat.succ_le_of_lt hlt)
  · rintro (rfl | hb)
    · simp [SimplyInfiniteSystem.numChain]
    · have hb' : S.equivNat a + 1 ≤ S.equivNat b := by
        simpa [SimplyInfiniteSystem.numChain, S.equivNat_succ] using hb
      simpa [SimplyInfiniteSystem.numChain] using Nat.le_of_succ_le hb'

theorem numChain_injective : Function.Injective S.numChain := by
  intro a b h
  have hab : S.equivNat a ≤ S.equivNat b := by
    have hbmem : b ∈ S.numChain b := by simp [SimplyInfiniteSystem.numChain]
    have : b ∈ S.numChain a := by
      simpa [h] using hbmem
    simpa using this
  have hba : S.equivNat b ≤ S.equivNat a := by
    have hamem : a ∈ S.numChain a := by simp [SimplyInfiniteSystem.numChain]
    have : a ∈ S.numChain b := by
      simpa [h] using hamem
    simpa using this
  exact S.equivNat.injective (Nat.le_antisymm hab hba)

theorem existsUnique_generator_of_numChain {K : Set α}
    (hK : ∃ a : α, K = S.numChain a) : ∃! a : α, K = S.numChain a := by
  rcases hK with ⟨a, rfl⟩
  refine ⟨a, rfl, ?_⟩
  intro b hb
  exact S.numChain_injective hb.symm

end SimplyInfiniteSystem

end Dedekind
end Foundations
end MathlibExpansion
