import Mathlib
import MathlibExpansion.Roots.Mazur1977.PrimeLevelHecke

/-!
# Eisenstein ideal (Mazur 1977 §6 — Ribet-consumed fragment)

At prime level `Γ₀(p)`, the Eisenstein ideal of the Hecke algebra `T` is
the ideal generated by `T_q - (q + 1)` as `q` ranges over primes `q ≠ p`.
A maximal ideal `𝔪 ⊂ T` is **Eisenstein** iff it contains the Eisenstein
ideal; equivalently, the residual eigensystem mod `𝔪` is congruent to the
Eisenstein series mod `𝔪`. Ribet 1990's level-lowering argument hinges on
the **non-Eisenstein** case: at a non-Eisenstein `𝔪`, the residual Galois
representation is irreducible and the residual attachment theorem applies.
The complementary Eisenstein-localized Gorenstein boundary is recorded in
`MultiplicityOne.lean` (historical filename).

**Doctrine v2 (poison-class dodges).**
- `EisensteinIdeal C` is built from honest ring data (`C.generator q -
  algebraMap R C.T (q + 1)`), not from a bare `Prop` parameter.
- `IsEisenstein C 𝔪` is the typed predicate `EisensteinIdeal C ≤ 𝔪`.
  Consumers discharge it by an ideal-membership check on the generators.
- `IsNonEisenstein` is simply `¬ IsEisenstein`. No T0/T1 laundering.
-/

namespace MathlibExpansion.Roots.Mazur1977

universe u v w

variable {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
variable {p : ℕ}

/-- **The Eisenstein ideal** of the prime-level Hecke carrier `C`: the
ideal of `C.T` generated by `T_q - (q + 1)` for all primes `q ≠ p`.

Recall (Mazur 1977): the Eisenstein series is a weight-2 Eisenstein
eigenform with `T_q` eigenvalue `q + 1` at all primes `q ≠ p`; the
Eisenstein ideal measures the congruence of an eigensystem with the
Eisenstein series. -/
noncomputable def EisensteinIdeal
    (C : PrimeLevelHeckeCarrier.{u,v,w} R M p) : Ideal C.T :=
  Ideal.span
    ((fun qh : {q : ℕ // q.Prime ∧ q ≠ p} =>
        C.generator qh - algebraMap R C.T ((qh.1 : R) + 1)) '' Set.univ)

/-- **Eisenstein maximal ideal.** A maximal ideal `𝔪 ⊂ T` is Eisenstein
iff it contains the Eisenstein ideal. -/
def IsEisenstein
    (C : PrimeLevelHeckeCarrier.{u,v,w} R M p) (𝔪 : Ideal C.T) : Prop :=
  EisensteinIdeal C ≤ 𝔪

/-- **Non-Eisenstein maximal ideal.** The Ribet-consumed case. -/
def IsNonEisenstein
    (C : PrimeLevelHeckeCarrier.{u,v,w} R M p) (𝔪 : Ideal C.T) : Prop :=
  ¬ IsEisenstein C 𝔪

/-- Generator membership: `T_q - (q+1)` is in the Eisenstein ideal. -/
theorem generator_sub_qplus1_mem_eisensteinIdeal
    (C : PrimeLevelHeckeCarrier.{u,v,w} R M p)
    (qh : {q : ℕ // q.Prime ∧ q ≠ p}) :
    C.generator qh - algebraMap R C.T ((qh.1 : R) + 1) ∈ EisensteinIdeal C := by
  apply Ideal.subset_span
  exact ⟨qh, Set.mem_univ _, rfl⟩

end MathlibExpansion.Roots.Mazur1977
