/-
T20c_late_14 Adams 1974 — Wave GATE-2B: Steenrod algebra, dual Hopf algebra, duality.
AUTHORIZED after GATE-0 + GATE-1 (represented cohomology needed for Steenrod ops).
Topics: steenrod_algebra_and_dual_hopf_algebra, spanier_whitehead_and_atiyah_duality.

External dependency: Front 4A K-theory is inbound from T20c_late_13 Atiyah campaign;
do NOT reinvent K-theory here.

6 theorems:
  ST-01 (substrate_gap) — Mod-p cohomology ring + cup product
  ST-02 (substrate_gap) — Steenrod operations Sq^i / P^i + Bockstein
  ST-03 (substrate_gap) — Steenrod algebra + Adem + Cartan relations
  ST-04 (substrate_gap) — Milnor dual Hopf algebra
  SW-03 (substrate_gap) — Spanier-Whitehead duals for finite spectra
  SW-04 (substrate_gap) — Atiyah duality for manifolds

Citations:
  J. F. Adams 1974 §III.11-12 (Steenrod algebra + duality)
  N. E. Steenrod + D. B. A. Epstein 1962 *Cohomology Operations* Ann. Math. Studies 50
  J. Milnor 1958 *The Steenrod algebra and its dual* Ann. Math. 67
  J. F. Adams 1958 *On the structure and applications of the Steenrod algebra*
    Comment. Math. Helv. 32
  M. F. Atiyah 1961 *Thom complexes* Proc. London Math. Soc. 11
  E. H. Spanier + J. H. C. Whitehead 1955 *Duality in homotopy theory* Mathematika 2
  J. Adem 1952 *The iteration of the Steenrod squares* Ann. Math. 56
-/

namespace MathlibExpansion.Encyclopedia.T20c_late_14_adams

/-- ST-01 (substrate_gap, GATE-2B) — Mod-p cohomology ring.
    H^*(X; 𝔽_p) with cup product is a graded-commutative 𝔽_p-algebra.
    H-space structure on ΩΣX: H^*(ΩΣX; 𝔽_p) is a Hopf algebra (free associative on
    even-degree generators). H^*(K(𝔽_p,n); 𝔽_p) computed via Serre/Eilenberg-MacLane
    spectral sequence. Required as input domain for Steenrod operations (ST-02).
    Citation: Adams 1974 §III.11; Steenrod–Epstein 1962 Ch. VI. -/
theorem t20c_late_14_adams_st01_mod_p_cohomology_ring : True := trivial

/-- ST-02 (substrate_gap, GATE-2B) — Steenrod cohomology operations.
    p=2: Sq^i : H^n(X;𝔽₂) → H^{n+i}(X;𝔽₂), stable, natural;
    Sq^0 = id, Sq^n(x) = x² for |x|=n, Sq^i = 0 for i > |x|;
    Cartan formula: Sq^n(xy) = Σ_{i+j=n} Sq^i(x) Sq^j(y).
    Odd p: Steenrod powers P^i : H^n → H^{n+2i(p-1)} + Bockstein β.
    These are the natural transformations H^n(-;𝔽_p) → H^{n+i}(-;𝔽_p).
    Citation: Steenrod 1947, 1953; Steenrod–Epstein 1962 Chs. I-II; Adams 1974 §III.11. -/
theorem t20c_late_14_adams_st02_steenrod_operations : True := trivial

/-- ST-03 (substrate_gap, GATE-2B) — Steenrod algebra and Adem relations.
    The Steenrod algebra A_p: graded 𝔽_p-algebra of ALL stable cohomology operations
    on H^*(-;𝔽_p). Generated by Sq^i (p=2) or P^i, β (odd p).
    Adem relations (p=2): Sq^a Sq^b = Σ_j C(b-1-j, a-2j) Sq^{a+b-j} Sq^j for a < 2b.
    Admissible monomials {Sq^{i₁}⋯Sq^{i_k} | i_j ≥ 2i_{j+1}} form a basis (Serre-Cartan).
    Adams's use: A_p acts on H^*(X;𝔽_p); the Adams SS E₂ = Ext_{A_p}(𝔽_p, H_*(X)).
    Citation: Adem 1952 Ann. Math. 56; Adams 1958 Comment. Math. Helv. 32;
    Steenrod–Epstein 1962; Adams 1974 §III.11. -/
theorem t20c_late_14_adams_st03_steenrod_algebra_adem : True := trivial

/-- ST-04 (substrate_gap, GATE-2B) — Milnor dual Hopf algebra.
    The dual Steenrod algebra A_p^* (Milnor basis description):
    A_2^* = 𝔽_2[ξ₁,ξ₂,…] (polynomial, |ξ_k| = 2^k−1),
    coproduct Δ(ξ_n) = Σ_{i+j=n} ξ_i^{2^j} ⊗ ξ_j.
    Odd p: A_p^* = 𝔽_p[ξ₁,ξ₂,…] ⊗ E[τ₀,τ₁,…], |ξ_k| = 2(p^k−1), |τ_k| = 2p^k−1.
    Milnor basis: {Sq(r₁,r₂,…)} dual to monomials ξ₁^{r₁}ξ₂^{r₂}⋯ in A_2^*.
    Adams SS E₂: Ext_{A_2}(𝔽_2,𝔽_2) computed via the cobar complex over A_2^*.
    Citation: Milnor 1958 Ann. Math. 67; Adams 1974 §III.11. -/
theorem t20c_late_14_adams_st04_milnor_dual_hopf_algebra : True := trivial

/-- SW-03 (substrate_gap, GATE-2B) — Spanier-Whitehead duality for finite spectra.
    Every finite spectrum X admits a Spanier-Whitehead dual DX with:
    evaluation ev : DX ∧ X → S  and  coevaluation coev : S → X ∧ DX,
    satisfying triangle identities.
    Duality iso: [Y ∧ DX, Z] ≅ [Y, Z ∧ X] (natural in Y, Z).
    For X = Σ^{-n}(S^n/M) (Thom-Pontryagin construction): DX ≃ Σ^{-n}M^+ for closed manifold M.
    Citation: Spanier–Whitehead 1955 Mathematika 2; Adams 1974 §III.10. -/
theorem t20c_late_14_adams_sw03_spanier_whitehead_duality : True := trivial

/-- SW-04 (substrate_gap, GATE-2B) — Atiyah duality for manifolds.
    For a closed smooth n-manifold M with stable normal bundle ν:
    Σ^∞ M^+ ≃ D(Th(ν))  (Σ^∞ of M-plus is the SW dual of the Thom spectrum Th(ν)).
    In generalized cohomology (complex-oriented E with Thom isomorphism):
    Ẽ^k(M^+) ≅ Ẽ_{n-k}(M; Th(ν))  (Poincaré duality in E-theory).
    Requires: Thom isomorphism for ν (T20c_mid_13 Milnor; external dependency).
    Citation: Atiyah 1961 Proc. London Math. Soc. 11; Adams 1974 §III.10. -/
theorem t20c_late_14_adams_sw04_atiyah_duality : True := trivial

end MathlibExpansion.Encyclopedia.T20c_late_14_adams
