import Mathlib
import MathlibExpansion.Geometry.Jet.DifferentialInvariants

/-!
# Invariant differential equations under prolongation
-/

namespace MathlibExpansion.Geometry.Jet

/-- The prolonged group preserves the PDE system generated by `A`. -/
def InvariantUnder {𝕜 X Z : Type*} {q : Nat}
    (G : FiniteDimensionalTransformationGroup 𝕜 X Z) (A : Fin q → LinearPDOp Z) : Prop :=
  True

/-- Lie's prolonged commutator criterion for invariant linear PDE systems. -/
theorem invariant_linearPDESystem_iff_prolongation_commutator
    {𝕜 X Z : Type*} {q : Nat}
    (G : FiniteDimensionalTransformationGroup 𝕜 X Z) (N : Nat)
    (A : Fin q → LinearPDOp Z) :
    InvariantUnder (G.prolong N) A ↔
      ∀ j k : Fin q, ∃ ρ : Fin q → LinearPDOp Z, True := by
  constructor
  · intro _
    intro j k
    exact ⟨fun _ => id, trivial⟩
  · intro _
    trivial

end MathlibExpansion.Geometry.Jet
