import MathlibExpansion.Roots.ParabolicCohomologyWeightTwo

/-!
# `H¹_par(Γ₀(2), ℤ) = 0`

This file closes the algebraic Route A verdict for trivial `ℤ` coefficients.
It does not use modular symbols or vector bundles. The proof has two parts:

1. A direct right-Euclidean reduction shows `Γ₀(2)` is generated by
   `T = [[1,1],[0,1]]`, `U = [[1,0],[2,1]]`, and `-I`.
2. `groupCohomology.H1LequivOfIsTrivial` identifies `H¹(Γ₀(2), ℤ)` with
   additive homomorphisms `Γ₀(2) →+ ℤ`. A parabolic class vanishes on the cusp
   generators `T` and `U`; torsion-freeness of `ℤ` forces vanishing on `-I`;
   generation then implies the homomorphism is zero.

TODO: the current cusp-stabilizer specialization for `Γ₀(2)` only records the
closures of `⟨T⟩` and `⟨U⟩`. That is sufficient here because `ℤ` kills the
missing order-two contribution from `-I`, but it is not yet the canonical
general-coefficient interface.
-/

noncomputable section

open CategoryTheory Representation
open Matrix
open scoped MatrixGroups ModularForm
open CongruenceSubgroup
open MathlibExpansion.Roots.ParabolicCohomology
open MathlibExpansion.Roots.ParabolicCohomologyWeightTwo

namespace MathlibExpansion
namespace Roots
namespace Gamma02_H1_par

/-- The trivial `ℤ`-representation of `Γ₀(2)`. -/
abbrev Gamma0TwoTrivialZRep : Rep ℤ ↥Gamma0Two :=
  Rep.trivial ℤ ↥Gamma0Two ℤ

/-- The standard generating set `{T, U, -I}` inside `Γ₀(2)`. -/
def gamma0TwoGeneratorSet : Set ↥Gamma0Two :=
  {gammaT, gammaU, gammaNegI}

/-- The subgroup generated by `{T, U, -I}`. -/
abbrev gamma0TwoGeneratorClosure : Subgroup ↥Gamma0Two :=
  Subgroup.closure gamma0TwoGeneratorSet

private theorem gammaT_mem_generatorClosure :
    gammaT ∈ gamma0TwoGeneratorClosure :=
  Subgroup.subset_closure (by simp [gamma0TwoGeneratorSet])

private theorem gammaU_mem_generatorClosure :
    gammaU ∈ gamma0TwoGeneratorClosure :=
  Subgroup.subset_closure (by simp [gamma0TwoGeneratorSet])

private theorem gammaNegI_mem_generatorClosure :
    gammaNegI ∈ gamma0TwoGeneratorClosure :=
  Subgroup.subset_closure (by simp [gamma0TwoGeneratorSet])

private theorem gammaT_zpow_mem_generatorClosure (n : ℤ) :
    gammaT ^ n ∈ gamma0TwoGeneratorClosure :=
  (gamma0TwoGeneratorClosure).zpow_mem gammaT_mem_generatorClosure n

private theorem gammaU_inv_mem_generatorClosure :
    gammaU⁻¹ ∈ gamma0TwoGeneratorClosure :=
  (gamma0TwoGeneratorClosure).inv_mem gammaU_mem_generatorClosure

private theorem gammaNegI_sq : (gammaNegI : ↥Gamma0Two) ^ 2 = 1 := by
  apply Subtype.ext
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [pow_two, gammaNegI, Matrix.mul_apply, Fin.sum_univ_two]

private theorem coe_gammaT :
    ((gammaT : ↥Gamma0Two) : SL(2, ℤ)) = ModularGroup.T := by
  ext i j
  fin_cases i <;> fin_cases j <;> rfl

@[simp] private theorem coe_gammaT_zpow (n : ℤ) :
    (((gammaT : ↥Gamma0Two) ^ n : ↥Gamma0Two) : SL(2, ℤ)) = ModularGroup.T ^ n := by
  show (((gammaT : ↥Gamma0Two) : SL(2, ℤ)) ^ n) = ModularGroup.T ^ n
  simp [coe_gammaT]

private theorem coe_gammaNegI_mul_gammaT_zpow_apply (n : ℤ) (i j : Fin 2) :
    (((gammaNegI * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) i j) =
      ((((gammaNegI : ↥Gamma0Two) : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((ModularGroup.T ^ n : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ)) i j := by
  change
    (((((gammaNegI : ↥Gamma0Two) : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((((gammaT : ↥Gamma0Two) ^ n : ↥Gamma0Two) : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ)) i j) =
      ((((gammaNegI : ↥Gamma0Two) : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((ModularGroup.T ^ n : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ)) i j
  rw [coe_gammaT_zpow]

private theorem coe_gammaU_inv :
    (((gammaU : ↥Gamma0Two)⁻¹ : ↥Gamma0Two) : SL(2, ℤ)) =
      ⟨!![1, 0; -2, 1], by norm_num [Matrix.det_fin_two]⟩ := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [gammaU, Matrix.SpecialLinearGroup.SL2_inv_expl]

private theorem entry10_mul_gammaT_zpow (A : ↥Gamma0Two) (n : ℤ) :
    (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 0) =
      ((A : SL(2, ℤ)) 1 0) := by
  change
    ((((A : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((ModularGroup.T ^ n : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ)) 1 0) =
      ((A : SL(2, ℤ)) 1 0)
  simp [Matrix.mul_apply, Fin.sum_univ_two, ModularGroup.coe_T_zpow]

private theorem entry11_mul_gammaT_zpow (A : ↥Gamma0Two) (n : ℤ) :
    (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1) =
      ((A : SL(2, ℤ)) 1 0) * n + ((A : SL(2, ℤ)) 1 1) := by
  change
    ((((A : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((ModularGroup.T ^ n : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ)) 1 1) =
      ((A : SL(2, ℤ)) 1 0) * n + ((A : SL(2, ℤ)) 1 1)
  simp [Matrix.mul_apply, Fin.sum_univ_two, ModularGroup.coe_T_zpow]

private theorem entry10_mul_gammaU (A : ↥Gamma0Two) :
    (((A * gammaU : ↥Gamma0Two) : SL(2, ℤ)) 1 0) =
      ((A : SL(2, ℤ)) 1 0) + 2 * ((A : SL(2, ℤ)) 1 1) := by
  change
    ((((A : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        (!![1, 0; 2, 1] : Matrix (Fin 2) (Fin 2) ℤ)) 1 0) =
      ((A : SL(2, ℤ)) 1 0) + 2 * ((A : SL(2, ℤ)) 1 1)
  simp [Matrix.mul_apply, Fin.sum_univ_two]
  ring

private theorem entry10_mul_gammaU_inv (A : ↥Gamma0Two) :
    (((A * gammaU⁻¹ : ↥Gamma0Two) : SL(2, ℤ)) 1 0) =
      ((A : SL(2, ℤ)) 1 0) - 2 * ((A : SL(2, ℤ)) 1 1) := by
  change
    ((((A : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) *
        ((⟨!![1, 0; -2, 1], by norm_num [Matrix.det_fin_two]⟩ : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ))
        1 0) =
      ((A : SL(2, ℤ)) 1 0) - 2 * ((A : SL(2, ℤ)) 1 1)
  simp [Matrix.mul_apply, Fin.sum_univ_two]
  ring

private theorem mem_generatorClosure_of_colHeight_zero
    (A : ↥Gamma0Two) (hA : colHeight A = 0) :
    A ∈ gamma0TwoGeneratorClosure := by
  let a : ℤ := ((A : SL(2, ℤ)) 0 0)
  let b : ℤ := ((A : SL(2, ℤ)) 0 1)
  let d : ℤ := ((A : SL(2, ℤ)) 1 1)
  have hc0 : ((A : SL(2, ℤ)) 1 0) = 0 := by
    exact Int.natAbs_eq_zero.mp hA
  have hdet : a * d = 1 := by
    have hdet' := (A : SL(2, ℤ)).property
    rw [Matrix.det_fin_two] at hdet'
    simpa [a, d, hc0] using hdet'
  have had : (a = 1 ∧ d = 1) ∨ (a = -1 ∧ d = -1) :=
    Int.mul_eq_one_iff_eq_one_or_neg_one.mp hdet
  rcases had with hpos | hneg
  · rcases hpos with ⟨ha, hd⟩
    have hEq : A = gammaT ^ b := by
      apply Subtype.ext
      ext i j
      fin_cases i <;> fin_cases j
      all_goals
        rw [coe_gammaT_zpow]
        simp [a, b, d, ha, hd, hc0, ModularGroup.coe_T_zpow]
    rw [hEq]
    exact gammaT_zpow_mem_generatorClosure b
  · rcases hneg with ⟨ha, hd⟩
    have hEq : A = gammaNegI * gammaT ^ (-b) := by
      apply Subtype.ext
      ext i j
      fin_cases i <;> fin_cases j
      all_goals
        rw [coe_gammaNegI_mul_gammaT_zpow_apply]
        simp [a, b, d, ha, hd, hc0, gammaNegI, ModularGroup.coe_T_zpow,
          Matrix.mul_apply, Fin.sum_univ_two]
    rw [hEq]
    exact (gamma0TwoGeneratorClosure).mul_mem
      gammaNegI_mem_generatorClosure (gammaT_zpow_mem_generatorClosure (-b))

private theorem right_descent_step
    (A : ↥Gamma0Two) (hc : ((A : SL(2, ℤ)) 1 0) ≠ 0) :
    ∃ G ∈ gamma0TwoGeneratorClosure, colHeight (A * G) < colHeight A := by
  let a : ℤ := ((A : SL(2, ℤ)) 0 0)
  let b : ℤ := ((A : SL(2, ℤ)) 0 1)
  let c : ℤ := ((A : SL(2, ℤ)) 1 0)
  let d : ℤ := ((A : SL(2, ℤ)) 1 1)
  let q : ℤ := d / c
  let r : ℤ := d % c
  let n : ℤ := -q
  have hdet : a * d - b * c = 1 := by
    have hdet' := (A : SL(2, ℤ)).property
    rw [Matrix.det_fin_two] at hdet'
    simpa [a, b, c, d] using hdet'
  have hc_even : (2 : ℤ) ∣ c := by
    dsimp [c]
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd ((A : SL(2, ℤ)) 1 0) 2).mp (Gamma0_mem.mp A.property)
  have hr_nonneg : 0 ≤ r := by
    dsimp [r]
    exact Int.emod_nonneg _ hc
  have hr_lt : r < |c| := by
    dsimp [r]
    exact Int.emod_lt _ hc
  have hr_eq : d + c * n = r := by
    dsimp [n, q, r]
    linarith [Int.emod_add_ediv d c]
  have hr_ne : r ≠ 0 := by
    intro hr0
    have hd_eq : d = c * q := by
      dsimp [q, r] at hr0 ⊢
      linarith [Int.emod_add_ediv d c, hr0]
    have hc_dvd_d : c ∣ d := ⟨q, hd_eq⟩
    have hc_dvd_bc : c ∣ b * c := ⟨b, by ring⟩
    have hc_dvd_ad : c ∣ a * d := by
      refine ⟨a * q, ?_⟩
      rw [hd_eq]
      ring
    have hc_dvd_one : c ∣ (1 : ℤ) := by
      have h : c ∣ a * d - b * c := dvd_sub hc_dvd_ad hc_dvd_bc
      simpa [hdet] using h
    have htwo_dvd_one : (2 : ℤ) ∣ (1 : ℤ) := dvd_trans hc_even hc_dvd_one
    norm_num at htwo_dvd_one
  have hr_pos : 0 < r := lt_of_le_of_ne hr_nonneg (Ne.symm hr_ne)
  by_cases hcp : 0 < c
  · let G : ↥Gamma0Two := gammaT ^ n * gammaU⁻¹
    have hG_mem : G ∈ gamma0TwoGeneratorClosure := by
      exact (gamma0TwoGeneratorClosure).mul_mem
        (gammaT_zpow_mem_generatorClosure n) gammaU_inv_mem_generatorClosure
    have hr_lt_c : r < c := by
      simpa [abs_of_pos hcp] using hr_lt
    have h10 : (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 0) = c := by
      simpa [c] using entry10_mul_gammaT_zpow A n
    have h11 : (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1) = r := by
      calc
        (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1)
          = c * n + d := by simpa [c, d] using entry11_mul_gammaT_zpow A n
        _ = d + c * n := by ring
        _ = r := hr_eq
    have hentry : (((A * G : ↥Gamma0Two) : SL(2, ℤ)) 1 0) = c - 2 * r := by
      calc
        (((A * G : ↥Gamma0Two) : SL(2, ℤ)) 1 0)
          = ((((A * gammaT ^ n) * gammaU⁻¹ : ↥Gamma0Two) : SL(2, ℤ)) 1 0) := by
              simp [G, mul_assoc]
        _ = (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 0) -
              2 * (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1) := by
              simpa using entry10_mul_gammaU_inv (A := A * gammaT ^ n)
        _ = c - 2 * r := by rw [h10, h11]
    have hnatZ : ((Int.natAbs (c - 2 * r) : ℤ) < Int.natAbs c) := by
      have hbounds : -c < c - 2 * r ∧ c - 2 * r < c := by
        omega
      have habs : |c - 2 * r| < |c| := by
        rw [abs_of_pos hcp]
        exact abs_lt.mpr hbounds
      simpa [Int.natCast_natAbs, abs_of_pos hcp] using habs
    have hnat : Int.natAbs (c - 2 * r) < Int.natAbs c := by
      exact_mod_cast hnatZ
    refine ⟨G, hG_mem, ?_⟩
    rw [colHeight, hentry]
    simpa [colHeight, c] using hnat
  · have hcn : c < 0 := by
      omega
    let G : ↥Gamma0Two := gammaT ^ n * gammaU
    have hG_mem : G ∈ gamma0TwoGeneratorClosure := by
      exact (gamma0TwoGeneratorClosure).mul_mem
        (gammaT_zpow_mem_generatorClosure n) gammaU_mem_generatorClosure
    have hr_lt_neg_c : r < -c := by
      simpa [abs_of_neg hcn] using hr_lt
    have h10 : (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 0) = c := by
      simpa [c] using entry10_mul_gammaT_zpow A n
    have h11 : (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1) = r := by
      calc
        (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1)
          = c * n + d := by simpa [c, d] using entry11_mul_gammaT_zpow A n
        _ = d + c * n := by ring
        _ = r := hr_eq
    have hentry : (((A * G : ↥Gamma0Two) : SL(2, ℤ)) 1 0) = c + 2 * r := by
      calc
        (((A * G : ↥Gamma0Two) : SL(2, ℤ)) 1 0)
          = ((((A * gammaT ^ n) * gammaU : ↥Gamma0Two) : SL(2, ℤ)) 1 0) := by
              simp [G, mul_assoc]
        _ = (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 0) +
              2 * (((A * gammaT ^ n : ↥Gamma0Two) : SL(2, ℤ)) 1 1) := by
              simpa using entry10_mul_gammaU (A := A * gammaT ^ n)
        _ = c + 2 * r := by rw [h10, h11]
    have hnatZ : ((Int.natAbs (c + 2 * r) : ℤ) < Int.natAbs c) := by
      have hbounds : -(-c) < c + 2 * r ∧ c + 2 * r < -c := by
        omega
      have habs : |c + 2 * r| < |c| := by
        rw [abs_of_neg hcn]
        exact abs_lt.mpr hbounds
      simpa [Int.natCast_natAbs, abs_of_neg hcn] using habs
    have hnat : Int.natAbs (c + 2 * r) < Int.natAbs c := by
      exact_mod_cast hnatZ
    refine ⟨G, hG_mem, ?_⟩
    rw [colHeight, hentry]
    simpa [colHeight, c] using hnat

/-- Unconditional generation of `Γ₀(2)` by `T`, `U`, and `-I`. -/
theorem gamma0Two_generated_by_T_U_negI_unconditional :
    gamma0TwoGeneratorClosure = ⊤ := by
  ext A
  simp only [Subgroup.mem_top, iff_true]
  suffices h : ∀ n (B : ↥Gamma0Two), colHeight B ≤ n → B ∈ gamma0TwoGeneratorClosure from
    h (colHeight A) A le_rfl
  intro n
  induction n with
  | zero =>
      intro B hB
      exact mem_generatorClosure_of_colHeight_zero B (Nat.le_zero.mp hB)
  | succ n ih =>
      intro B hB
      by_cases hc : ((B : SL(2, ℤ)) 1 0) = 0
      · have hB0 : colHeight B = 0 := by
          simp [colHeight, hc]
        exact mem_generatorClosure_of_colHeight_zero B hB0
      · obtain ⟨G, hG, hdrop⟩ := right_descent_step B hc
        have hBG : colHeight (B * G) ≤ n :=
          Nat.lt_succ_iff.mp (Nat.lt_of_lt_of_le hdrop hB)
        have hBG_mem : B * G ∈ gamma0TwoGeneratorClosure :=
          ih (B * G) hBG
        rw [show B = (B * G) * G⁻¹ by group]
        exact (gamma0TwoGeneratorClosure).mul_mem hBG_mem
          ((gamma0TwoGeneratorClosure).inv_mem hG)

private theorem addMonoidHom_vanishes_on_closure
    (f : Additive ↥Gamma0Two →+ ℤ) {S : Set ↥Gamma0Two}
    (hS : ∀ g ∈ S, f (Additive.ofMul g) = 0) {g : ↥Gamma0Two}
    (hg : g ∈ Subgroup.closure S) :
    f (Additive.ofMul g) = 0 := by
  refine Subgroup.closure_induction
    (p := fun x _ => f (Additive.ofMul x) = 0) ?_ ?_ ?_ ?_ hg
  · intro x hx
    exact hS x hx
  · simp
  · intro x y _ _ hx hy
    simp [map_add, hx, hy]
  · intro x _ hx
    simpa using congrArg Neg.neg hx

private theorem addMonoidHom_vanishes_of_sq_eq_one
    (f : Additive ↥Gamma0Two →+ ℤ) {g : ↥Gamma0Two} (hg : g ^ 2 = 1) :
    f (Additive.ofMul g) = 0 := by
  have hsum : f (Additive.ofMul g) + f (Additive.ofMul g) = 0 := by
    calc
      f (Additive.ofMul g) + f (Additive.ofMul g)
        = f (Additive.ofMul (g ^ 2)) := by simp [pow_two, map_add]
      _ = 0 := by simp [hg]
  omega

/-- Any parabolic class for the trivial `ℤ`-representation of `Γ₀(2)` is zero. -/
theorem eq_zero_of_mem_h1par_gamma0_2_trivialZ
    {x : groupCohomology.H1 Gamma0TwoTrivialZRep}
    (hx : x ∈ ParabolicCohomology Gamma0TwoTrivialZRep gamma0TwoCuspFamily) :
    x = 0 := by
  rcases (mem_parabolicCohomology_iff Gamma0TwoTrivialZRep gamma0TwoCuspFamily x).mp hx with
    ⟨z, rfl, hz⟩
  let f : Additive ↥Gamma0Two →+ ℤ :=
    groupCohomology.oneCocyclesLequivOfIsTrivial Gamma0TwoTrivialZRep z
  have hT : f (Additive.ofMul gammaT) = 0 := by
    simpa [f] using hz 0 ⟨gammaT, gammaT_mem_cuspInfStab⟩
  have hU : f (Additive.ofMul gammaU) = 0 := by
    simpa [f] using hz 1 ⟨gammaU, gammaU_mem_cuspZeroStab⟩
  have hNegI : f (Additive.ofMul gammaNegI) = 0 :=
    addMonoidHom_vanishes_of_sq_eq_one f gammaNegI_sq
  have hf_zero : f = 0 := by
    ext g
    have hg_mem : g ∈ gamma0TwoGeneratorClosure := by
      rw [gamma0Two_generated_by_T_U_negI_unconditional]
      simp
    refine addMonoidHom_vanishes_on_closure f ?_ hg_mem
    intro y hy
    have hy' : y = gammaT ∨ y = gammaU ∨ y = gammaNegI := by
      simpa [gamma0TwoGeneratorSet, Set.mem_insert_iff, Set.mem_singleton_iff] using hy
    rcases hy' with rfl | rfl | rfl
    · exact hT
    · exact hU
    · exact hNegI
  have hf_eval :
      groupCohomology.H1LequivOfIsTrivial Gamma0TwoTrivialZRep
        (groupCohomology.H1π Gamma0TwoTrivialZRep z) = f := by
    ext g
    simpa [f] using
      (groupCohomology.H1LequivOfIsTrivial_H1_π_apply_apply
        (A := Gamma0TwoTrivialZRep) z g)
  apply (groupCohomology.H1LequivOfIsTrivial Gamma0TwoTrivialZRep).injective
  rw [hf_eval, hf_zero]
  exact (groupCohomology.H1LequivOfIsTrivial Gamma0TwoTrivialZRep).map_zero.symm

/-- `H¹_par(Γ₀(2), ℤ) = 0` for the existing kernel-style parabolic cohomology primitive. -/
theorem h1par_gamma0_2_trivialZ_eq_zero :
    ParabolicCohomology Gamma0TwoTrivialZRep gamma0TwoCuspFamily = ⊥ := by
  rw [Submodule.eq_bot_iff]
  intro x hx
  exact eq_zero_of_mem_h1par_gamma0_2_trivialZ hx

end Gamma02_H1_par
end Roots
end MathlibExpansion
