import MathlibExpansion.Roots.ParabolicCohomology
import MathlibExpansion.SturmBound

open Matrix
open scoped MatrixGroups ModularForm

/-!
# Weight-Two Parabolic Cohomology for Γ₀(2) — W2 Consensus (board-w2-20260420-03 R5)

Implements the Round-5 boardroom consensus:

**LHS (group-theoretic, fully closeable):**
- `Gamma0Two` alias for `CongruenceSubgroup.Gamma0 2`
- Bundled generators `gammaT`, `gammaU`, `gammaNegI`
  Membership via `Gamma0_mem : A ∈ Gamma0 N ↔ (A 1 0 : ZMod N) = 0`
- `colHeight` Euclidean descent measure
- `Gamma0Two_generated_by_T_U_negI` via Nat.rec on a colHeight bound
- Cusp stabilizers at ∞ and 0 via `Subgroup.closure`
- `ParabolicCohomologyWeightTwoSubmodule` over any `Rep ℂ ↥Gamma0Two`

**Honest-wall primitives (named `Prop`, not `axiom`):**
- `EuclideanDescentStepPrimitive`
- `ClosureBaseStepPrimitive`
- `S2Gamma0TwoZeroPrimitive` — equivalent to `SturmDimensionBoundPrimitive`

**Single Mathlib gap:** `SturmDimensionBoundPrimitive`.
-/

namespace MathlibExpansion
namespace Roots
namespace ParabolicCohomologyWeightTwo

noncomputable section

open CongruenceSubgroup
open MathlibExpansion.Roots.ParabolicCohomology
open MathlibExpansion.SturmBound

/-! ## Section 1: Γ₀(2) alias and generators

`Gamma0_mem : A ∈ Gamma0 N ↔ (A 1 0 : ZMod N) = 0`
(from Mathlib.NumberTheory.ModularForms.CongruenceSubgroups)

Membership proofs: `show` removes proof terms from the goal, then `decide` handles
the finite `ZMod 2` computation.
-/

/-- Γ₀(2) as a subgroup of SL(2,ℤ). -/
abbrev Gamma0Two : Subgroup SL(2, ℤ) := CongruenceSubgroup.Gamma0 2

/-- T = [[1,1],[0,1]] ∈ Γ₀(2). Entry (1,0) = 0; (0 : ZMod 2) = 0. -/
def gammaT : ↥Gamma0Two :=
  ⟨⟨!![1, 1; 0, 1], by norm_num [Matrix.det_fin_two]⟩,
   Gamma0_mem.mpr (by native_decide)⟩

/-- U = [[1,0],[2,1]] ∈ Γ₀(2). Entry (1,0) = 2; (2 : ZMod 2) = 0. -/
def gammaU : ↥Gamma0Two :=
  ⟨⟨!![1, 0; 2, 1], by norm_num [Matrix.det_fin_two]⟩,
   Gamma0_mem.mpr (by native_decide)⟩

/-- -I = [[-1,0],[0,-1]] ∈ Γ₀(2). Entry (1,0) = 0; (0 : ZMod 2) = 0. -/
def gammaNegI : ↥Gamma0Two :=
  ⟨⟨!![-1, 0; 0, -1], by norm_num [Matrix.det_fin_two]⟩,
   Gamma0_mem.mpr (by native_decide)⟩

/-! ## Section 2: Euclidean descent measure -/

/-- The Euclidean descent measure: |A 1 0| for A : Γ₀(2). -/
def colHeight (A : ↥Gamma0Two) : ℕ :=
  Int.natAbs ((A : SL(2, ℤ)) 1 0)

@[simp]
theorem colHeight_gammaT : colHeight gammaT = 0 := by native_decide

@[simp]
theorem colHeight_gammaU : colHeight gammaU = 2 := by native_decide

@[simp]
theorem colHeight_gammaNegI : colHeight gammaNegI = 0 := by native_decide

/-! ## Section 3: Honest-wall primitives and the closure theorem -/

/-- **EuclideanDescentStepPrimitive** — for A : Γ₀(2) with A 1 0 ≠ 0,
some product of {T,U,-I} strictly reduces colHeight.

Math: 2 ∣ c, det = 1 → gcd(c,d) = 1 → d odd → right-mult by U^k reduces |c|.
Lean gap: nonlinear integer Euclidean descent lemma not packaged in v4.17.0. -/
def EuclideanDescentStepPrimitive : Prop :=
  ∀ A : ↥Gamma0Two,
    ((A : SL(2, ℤ)) 1 0 ≠ 0) →
    ∃ G ∈ Subgroup.closure ({gammaT, gammaU, gammaNegI} : Set ↥Gamma0Two),
      colHeight (G * A) < colHeight A

/-- **ClosureBaseStepPrimitive** — A with colHeight 0 lies in closure{T,U,-I}.

Math: c = 0 → A = ±T^b. Lean gap: induction on b, ~30 lines. -/
def ClosureBaseStepPrimitive : Prop :=
  ∀ A : ↥Gamma0Two,
    colHeight A = 0 →
    A ∈ Subgroup.closure ({gammaT, gammaU, gammaNegI} : Set ↥Gamma0Two)

/-- **Gamma0Two_generated_by_T_U_negI** — Γ₀(2) = ⟨T, U, -I⟩.

Proved by ordinary Nat.rec on a colHeight bound `n`. -/
theorem Gamma0Two_generated_by_T_U_negI
    (hstep : EuclideanDescentStepPrimitive)
    (hbase : ClosureBaseStepPrimitive) :
    Subgroup.closure ({gammaT, gammaU, gammaNegI} : Set ↥Gamma0Two) = ⊤ := by
  ext A
  simp only [Subgroup.mem_top, iff_true]
  suffices h : ∀ (n : ℕ) (B : ↥Gamma0Two), colHeight B ≤ n →
      B ∈ Subgroup.closure ({gammaT, gammaU, gammaNegI} : Set ↥Gamma0Two) from
    h (colHeight A) A le_rfl
  intro n
  induction n with
  | zero =>
    intro B hB
    exact hbase B (Nat.le_zero.mp hB)
  | succ n ih =>
    intro B hB
    by_cases hc : (B : SL(2, ℤ)) 1 0 = 0
    · exact hbase B (by simp [colHeight, hc])
    · obtain ⟨G, hGcl, hdrop⟩ := hstep B hc
      have hle : colHeight (G * B) ≤ n :=
        Nat.lt_succ_iff.mp (Nat.lt_of_lt_of_le hdrop hB)
      have hGA_mem : G * B ∈
          Subgroup.closure ({gammaT, gammaU, gammaNegI} : Set ↥Gamma0Two) :=
        ih (G * B) hle
      rw [show B = G⁻¹ * (G * B) from by group]
      exact (Subgroup.closure _).mul_mem (Subgroup.inv_mem _ hGcl) hGA_mem

/-! ## Section 4: Cusp stabilizers -/

/-- Cusp stabilizer at ∞: generated by T = [[1,1],[0,1]]. Width 1. -/
def cuspInfStab : Subgroup ↥Gamma0Two :=
  Subgroup.closure ({gammaT} : Set ↥Gamma0Two)

/-- Cusp stabilizer at 0: generated by U = [[1,0],[2,1]]. Width 2. -/
def cuspZeroStab : Subgroup ↥Gamma0Two :=
  Subgroup.closure ({gammaU} : Set ↥Gamma0Two)

theorem gammaT_mem_cuspInfStab : gammaT ∈ cuspInfStab :=
  Subgroup.subset_closure (Set.mem_singleton _)

theorem gammaU_mem_cuspZeroStab : gammaU ∈ cuspZeroStab :=
  Subgroup.subset_closure (Set.mem_singleton _)

/-! ## Section 5: Weight-two parabolic cohomology submodule -/

/-- Two-cusp family for Γ₀(2): index 0 → ∞-stabilizer, index 1 → 0-stabilizer. -/
def gamma0TwoCuspFamily : Fin 2 → Subgroup ↥Gamma0Two
  | 0 => cuspInfStab
  | 1 => cuspZeroStab

@[simp]
theorem gamma0TwoCuspFamily_zero : gamma0TwoCuspFamily 0 = cuspInfStab := rfl

@[simp]
theorem gamma0TwoCuspFamily_one : gamma0TwoCuspFamily 1 = cuspZeroStab := rfl

/-- Weight-two parabolic cohomology for Γ₀(2), for any `A : Rep ℂ ↥Gamma0Two`.

Specializes `ParabolicCohomology` to the two cusps {∞, 0} of Γ₀(2).
At weight 2, A is the trivial ℂ-representation. -/
def ParabolicCohomologyWeightTwoSubmodule (A : Rep ℂ ↥Gamma0Two) :
    Submodule ℂ (groupCohomology.H1 A) :=
  ParabolicCohomology A gamma0TwoCuspFamily

/-- A class is parabolic iff it has a cocycle restricting to a coboundary at each cusp. -/
theorem mem_parabolicWeightTwo_iff (A : Rep ℂ ↥Gamma0Two)
    (x : groupCohomology.H1 A) :
    x ∈ ParabolicCohomologyWeightTwoSubmodule A ↔
      ∃ z : groupCohomology.oneCocycles A,
        groupCohomology.H1π A z = x ∧
        OneCocycleVanishesOn A gamma0TwoCuspFamily z :=
  mem_parabolicCohomology_iff A _ x

/-! ## Section 6: S₂(Γ₀(2)) = 0 connection -/

/-- `S₂(Γ₀(2)) = 0`. Arithmetic in SturmBound.lean: dim ≤ ⌊2·3/12⌋ = 0.
Gap: `SturmDimensionBoundPrimitive` (Diamond–Shurman §3.1, not in Mathlib v4.17.0). -/
def S2Gamma0TwoZeroPrimitive : Prop :=
  Module.finrank ℂ (CuspForm (CongruenceSubgroup.Gamma0 2) 2) = 0

theorem s2_zero_of_sturm (h : SturmDimensionBoundPrimitive) :
    S2Gamma0TwoZeroPrimitive :=
  MathlibExpansion.SturmBound.dim_S2_eq_zero_of_sturm_primitive h

theorem sturm_iff_s2_zero
    [FiniteDimensional ℂ (CuspForm (CongruenceSubgroup.Gamma0 2) 2)] :
    SturmDimensionBoundPrimitive ↔ S2Gamma0TwoZeroPrimitive := by
  constructor
  · exact s2_zero_of_sturm
  · intro h
    unfold SturmDimensionBoundPrimitive S2Gamma0TwoZeroPrimitive at *
    rw [MathlibExpansion.SturmBound.sturmDimensionBound_gamma0_two_weight_two]
    omega

end  -- closes noncomputable section

end ParabolicCohomologyWeightTwo
end Roots
end MathlibExpansion

section ExportedChecks
open MathlibExpansion.Roots.ParabolicCohomologyWeightTwo

#check Gamma0Two
#check gammaT
#check gammaU
#check gammaNegI
#check colHeight
#check colHeight_gammaT
#check colHeight_gammaU
#check colHeight_gammaNegI
#check EuclideanDescentStepPrimitive
#check ClosureBaseStepPrimitive
#check Gamma0Two_generated_by_T_U_negI
#check cuspInfStab
#check cuspZeroStab
#check gammaT_mem_cuspInfStab
#check gammaU_mem_cuspZeroStab
#check gamma0TwoCuspFamily
#check ParabolicCohomologyWeightTwoSubmodule
#check mem_parabolicWeightTwo_iff
#check S2Gamma0TwoZeroPrimitive
#check s2_zero_of_sturm
#check sturm_iff_s2_zero

end ExportedChecks
