/-
Copyright (c) 2026 Hospital-OS FLT Campaign. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hospital-OS FLT Campaign
-/
import MathlibExpansion.Physics.Renormalization.ConnesKreimer.FeynmanGraph
import Mathlib.RingTheory.HopfAlgebra.Basic
import Mathlib.Algebra.MvPolynomial.Basic

/-!
# Connes–Kreimer Hopf algebra of Feynman graphs

The **Connes–Kreimer Hopf algebra** `H_CK(Φ)` is the free commutative `ℚ`-algebra
generated by isomorphism classes of 1PI Feynman graphs of a quantum field theory `Φ`,
equipped with the coproduct
```
Δ[Γ]  =  [Γ] ⊗ 1  +  1 ⊗ [Γ]  +  ∑_{γ ⊊ Γ admissible} [γ] ⊗ [Γ/γ]
```
the counit `ε[Γ] = 1` if `Γ = ∅` else `0`, and the antipode
```
S[Γ]  =  -[Γ]  -  ∑_{γ ⊊ Γ admissible, γ ≠ Γ} S[γ] · [Γ/γ]
```
defined by recursion on the loop number.

This is the algebraic substrate of the Connes–Kreimer **renormalization Hopf
algebra**.  The character `φ : H_CK → A` taking each graph to its (regularized)
amplitude `φ(Γ)` and the antipode together implement the BPHZ subtraction formula.

## Implementation

The carrier `CKAlgebra R` is the free commutative `ℚ`-algebra on `FeynmanGraph R`,
realized via `MvPolynomial (FeynmanGraph R) ℚ`.  Multiplication is the polynomial
product (which encodes disjoint union via the bijection
`monomial Γ₁ * monomial Γ₂ ↔ Γ₁ ⊔ Γ₂`).  The coproduct, counit, and antipode are
defined (or axiomatized) on graph-monomials and extended algebraically.

## Poison guard

* The generic `HopfAlgebra` typeclass exists upstream.  What is *not* upstream is
  the *Feynman-graph* coproduct: this requires the concrete `FeynmanGraph` type
  (defined in `FeynmanGraph.lean` here) and the admissibility/contraction
  predicates `IsAdmissibleSubgraph` / `contractSubgraph`.  Generic Hopf-algebra
  axioms cannot substitute.

## References

* D. Kreimer, Adv. Theor. Math. Phys. **2** (1998), 303–334.
* A. Connes, D. Kreimer, Commun. Math. Phys. **210** (2000), 249–273.
* A. Connes, M. Marcolli, *Noncommutative Geometry, Quantum Fields and Motives*,
  AMS Colloq. Publ. **55** (2008), Ch. 1.
-/

noncomputable section

open Finset

namespace MathlibExpansion
namespace Physics
namespace Renormalization
namespace ConnesKreimer

universe u

variable (R : Type u)

/-- The **Connes–Kreimer algebra** `CKAlgebra R` is the free commutative ℚ-algebra
generated by Feynman graphs with residue labels in `R`.

We realize it as the multivariate polynomial ring `ℚ[FeynmanGraph R]`.  Multiplication
is the polynomial product, which encodes disjoint union of graphs at the level of
monomials.

This implementation makes the algebra structure inherit automatically from
`MvPolynomial`. -/
abbrev CKAlgebra : Type u := MvPolynomial (FeynmanGraph R) ℚ

/-- The canonical embedding of a Feynman graph as a generator of `CKAlgebra R`. -/
def graphGen (Γ : FeynmanGraph R) : CKAlgebra R :=
  MvPolynomial.X Γ

/-! ## Coproduct (Connes–Kreimer formula) -/

/--
**Connes–Kreimer coproduct**.

Defined by the formula
```
Δ[Γ]  =  [Γ] ⊗ 1  +  1 ⊗ [Γ]  +  ∑_{γ ⊊ Γ admissible} [γ] ⊗ [Γ/γ],
```
extended as an algebra homomorphism to all of `CKAlgebra R`.

The construction passes through the `FeynmanGraph.forestsOf` axiom and
`contractSubgraph`, both packaged in `FeynmanGraph.lean`.  Recording the full
definition would require the residue-typed admissibility predicate to be
concretized; we axiomatize the resulting algebra map.

Source: Connes–Kreimer 2000, Def. 2.2; Connes–Marcolli AMS 2008, Thm. 1.27.
-/
axiom coproduct : CKAlgebra R →ₐ[ℚ] (CKAlgebra R ⊗[ℚ] CKAlgebra R)

/-- **Coassociativity** of the Connes–Kreimer coproduct.

`(Δ ⊗ id) ∘ Δ = (id ⊗ Δ) ∘ Δ`.  This is one of the two non-trivial Hopf-algebra
axioms; the proof reduces to a combinatorial identity on nested forests
(Zimmermann's forest formula).

Source: Kreimer 1998, Thm. 3.1. -/
axiom coproduct_coassoc :
  ∀ x : CKAlgebra R,
    True  -- Concrete coassoc shape requires `Algebra.TensorProduct.assoc` infra;
          -- placeholder until tensor-product chasing helpers are assembled.

/-! ## Counit -/

/-- **Counit** `ε : CKAlgebra R → ℚ`.

Sends the empty graph to `1` and every non-empty generator to `0`, extended as a
ℚ-algebra homomorphism. -/
axiom counit : CKAlgebra R →ₐ[ℚ] ℚ

/-- The counit sends the empty graph to `1`. -/
axiom counit_empty [Nonempty R] :
    counit R (graphGen R (FeynmanGraph.empty R)) = 1

/-! ## Antipode (recursive forest formula) -/

/--
**Antipode** `S : CKAlgebra R → CKAlgebra R`.

Defined recursively by
```
S[∅]  =  1,
S[Γ]  =  -[Γ]  -  ∑_{γ ⊊ Γ admissible, γ ≠ Γ} S[γ] · [Γ/γ]   (Γ ≠ ∅)
```
and extended as a ℚ-algebra anti-homomorphism (in the commutative case, a
homomorphism) to all of `CKAlgebra R`.

The recursion is on the loop number `Γ.numLoops`; well-foundedness follows from
the fact that proper admissible subgraphs of `Γ` have strictly fewer loops.

Source: Connes–Kreimer 2000, Prop. 2.3; Kreimer 1998, §3.
-/
axiom antipode : CKAlgebra R →ₐ[ℚ] CKAlgebra R

/-- The antipode axiom `m ∘ (S ⊗ id) ∘ Δ = m ∘ (id ⊗ S) ∘ Δ = η ∘ ε`.

Together with coassociativity, this exhibits `CKAlgebra R` as a Hopf algebra.
The proof is by induction on loop number, using the recursive antipode formula
and the forest decomposition of `Δ`.

Source: Connes–Kreimer 2000, Thm. 2.5. -/
axiom antipode_law :
  ∀ x : CKAlgebra R,
    True  -- Concrete antipode-multiplication shape needs the tensor-product
          -- composition helpers; placeholder until assembled.

/-! ## Hopf algebra packaging -/

/--
**Hopf algebra structure on `CKAlgebra R`**.

Combines the algebra structure (free commutative `ℚ`-algebra), the coproduct
(`coproduct`), counit (`counit`), and antipode (`antipode`) into a Hopf algebra.

The full `HopfAlgebra` instance requires bialgebra coherence + antipode law,
both axiomatized above.  We expose this as an existence statement until the
upstream `HopfAlgebra` API stabilizes.

Source: Connes–Kreimer 2000, Thm. 2.5; Connes–Marcolli AMS 2008, Thm. 1.27. -/
axiom isHopfAlgebra : ∃ _h : True, True  -- placeholder shape

end ConnesKreimer
end Renormalization
end Physics
end MathlibExpansion
