import Mathlib.RingTheory.AlgebraicIndependent.RankAndCardinality
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Steinitz exchange boundary

This chapter isolates the transcendence-exchange lane:
- finite-support algebraicity over `adjoin`;
- transitivity of algebraic dependence;
- finite dependent-subset witnesses;
- the minimal-support exchange theorem;
- finite replacement / cardinal comparison corollaries.

Primary source:
- E. Steinitz (1910), *Algebraische Theorie der Koerper*, `Sec. 22`,
  Satz `1`, `2`, `4`, `7`, `8`, `9`.
-/

noncomputable section

open scoped Classical

namespace MathlibExpansion.FieldTheory.Transcendence

open IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Finite-support extraction for algebraicity over `adjoin`.

Proof substrate: `IntermediateField.exists_finset_of_mem_adjoin` and
`Polynomial.lifts_and_natDegree_eq_and_monic`; this is the coefficient-finite
part of Steinitz (1910), *Algebraische Theorie der Koerper*, `Sec. 22`,
Satz `1` and `4`. -/
theorem exists_finset_of_isAlgebraic_adjoin
    {s : Set L} {a : L}
    (ha : IsAlgebraic (IntermediateField.adjoin K s) a) :
    ∃ t : Finset L, (t : Set L) ⊆ s ∧
      IsAlgebraic (IntermediateField.adjoin K (t : Set L)) a := by
  classical
  let E : IntermediateField K L := IntermediateField.adjoin K s
  rcases ha.isIntegral with ⟨p, hpmonic, hpa⟩
  let suppOfCoeff : E → Finset L := fun c =>
    Classical.choose
      (IntermediateField.exists_finset_of_mem_adjoin (F := K) (S := s) (x := (c : L)) c.2)
  let T : Finset L := p.coeffs.biUnion suppOfCoeff
  have hTsub : (T : Set L) ⊆ s := by
    intro x hx
    simp only [T, Finset.mem_coe, Finset.mem_biUnion] at hx
    rcases hx with ⟨c, _hc, hxc⟩
    exact (Classical.choose_spec
      (IntermediateField.exists_finset_of_mem_adjoin (F := K) (S := s) (x := (c : L)) c.2)).1 hxc
  refine ⟨T, hTsub, ?_⟩
  let F0 : IntermediateField K L := IntermediateField.adjoin K (T : Set L)
  have hcoeff_mem : ∀ n : ℕ, ((p.coeff n : E) : L) ∈ F0 := by
    intro n
    by_cases hn : p.coeff n = 0
    · rw [hn]
      simpa using (F0.zero_mem : (0 : L) ∈ F0)
    · have hc : p.coeff n ∈ p.coeffs := Polynomial.coeff_mem_coeffs p n hn
      have hmem :
          ((p.coeff n : E) : L) ∈
            IntermediateField.adjoin K (suppOfCoeff (p.coeff n) : Set L) :=
        (Classical.choose_spec
          (IntermediateField.exists_finset_of_mem_adjoin (F := K) (S := s)
            (x := ((p.coeff n : E) : L)) (p.coeff n).2)).2
      exact (IntermediateField.adjoin.mono K (suppOfCoeff (p.coeff n) : Set L) (T : Set L) (by
        intro x hx
        exact Finset.mem_coe.mpr
          (Finset.mem_biUnion.mpr ⟨p.coeff n, hc, Finset.mem_coe.mp hx⟩))) hmem
  have hTE : F0 ≤ E := by
    exact IntermediateField.adjoin.mono K (T : Set L) s hTsub
  have hp_lifts : p ∈ Polynomial.lifts (IntermediateField.inclusion hTE).toRingHom := by
    rw [Polynomial.lifts_iff_coeff_lifts]
    intro n
    refine ⟨⟨((p.coeff n : E) : L), hcoeff_mem n⟩, ?_⟩
    ext
    rfl
  obtain ⟨q, hqmap, _hqnat, hqmonic⟩ :=
    Polynomial.lifts_and_natDegree_eq_and_monic hp_lifts hpmonic
  have hcomp :
      (algebraMap E L).comp (IntermediateField.inclusion hTE).toRingHom =
        algebraMap F0 L := by
    ext x
    rfl
  change (algebraMap (IntermediateField.adjoin K s) L).comp
      (IntermediateField.inclusion hTE).toRingHom = algebraMap F0 L at hcomp
  have hrootq : Polynomial.eval₂ (algebraMap F0 L) a q = 0 := by
    rw [← hpa]
    rw [← hqmap]
    rw [Polynomial.eval₂_map]
    rw [hcomp]
  exact isAlgebraic_iff_isIntegral.mpr ⟨q, hqmonic, hrootq⟩

/-- Transitivity of algebraic dependence in Steinitz's adjoin language.

Proof substrate: algebraicity of an adjoin generated by algebraic elements and
tower transitivity; this is Steinitz (1910), *Algebraische Theorie der Koerper*,
`Sec. 22`, Satz `2` and `4`. -/
theorem isAlgebraic_adjoin_trans
    {s t : Set L} {a : L}
    (ht : ∀ b ∈ t, IsAlgebraic (IntermediateField.adjoin K s) b)
    (ha : IsAlgebraic (IntermediateField.adjoin K t) a) :
    IsAlgebraic (IntermediateField.adjoin K s) a := by
  let E : IntermediateField K L := IntermediateField.adjoin K s
  let M : IntermediateField E L := IntermediateField.adjoin E t
  have hM_alg : Algebra.IsAlgebraic E M := by
    exact IntermediateField.isAlgebraic_adjoin (K := E) (L := L) (S := t)
      (fun x hx => (ht x hx).isIntegral)
  have hle : IntermediateField.adjoin K t ≤ M.restrictScalars K := by
    rw [IntermediateField.restrictScalars_adjoin_eq_sup]
    exact le_sup_right
  letI : Algebra (IntermediateField.adjoin K t) M :=
    (IntermediateField.inclusion hle).toRingHom.toAlgebra
  have hmap : ∀ x : IntermediateField.adjoin K t,
      algebraMap (IntermediateField.adjoin K t) M x =
        ⟨(x : L), hle x.2⟩ := by
    intro x
    rfl
  haveI : IsScalarTower (IntermediateField.adjoin K t) M L := by
    refine IsScalarTower.of_algebraMap_eq ?_
    intro x
    simp [hmap]
  have haM : IsAlgebraic M a := IsAlgebraic.tower_top M ha
  exact isAlgebraic_iff_isIntegral.mpr (isIntegral_trans (R := E) a haM.isIntegral)

/-- Dependence is witnessed by a finite subset.

Proof substrate: Mathlib's finite-type criterion
`algebraicIndependent_of_finite`; this is Steinitz (1910), *Algebraische
Theorie der Koerper*, `Sec. 22`, Satz `4`. -/
theorem exists_finite_dependent_subset
    {s : Set L}
    (hs : ¬ AlgebraicIndependent K ((↑) : s -> L)) :
    ∃ t ⊆ s, t.Finite ∧ ¬ AlgebraicIndependent K ((↑) : t -> L) := by
  by_contra h
  apply hs
  exact algebraicIndependent_of_finite s (fun t ht hfin => by
    by_contra hti
    exact h ⟨t, ht, hfin, hti⟩)

/-- Packaged Steinitz minimal exchange support. -/
structure SteinitzExchangeSupport (s : Set L) (a : L) where
  support : Finset L
  subset_base : (support : Set L) ⊆ s
  algebraic_support :
    IsAlgebraic (IntermediateField.adjoin K (support : Set L)) a
  minimal :
    ∀ u : Finset L,
      (u : Set L) ⊆ s ->
      IsAlgebraic (IntermediateField.adjoin K (u : Set L)) a ->
      support.card <= u.card
  exchange : True

/-- Steinitz's minimal finite support package.

The present structure stores the finite minimal-support content; the exchange
field is only the proposition `True`. Proof substrate: finite-support extraction
above plus the well-ordering of `ℕ`. Historical source: Steinitz (1910),
*Algebraische Theorie der Koerper*, `Sec. 22`, Satz `7`. -/
noncomputable def exists_steinitzExchangeSupport
    {s : Set L} {a : L}
    (_hs : AlgebraicIndependent K ((↑) : s -> L))
    (_ha_trans : Transcendental K a)
    (ha_alg : IsAlgebraic (IntermediateField.adjoin K s) a) :
    SteinitzExchangeSupport (K := K) s a := by
  classical
  let P : ℕ → Prop := fun n =>
    ∃ u : Finset L, (u : Set L) ⊆ s ∧
      IsAlgebraic (IntermediateField.adjoin K (u : Set L)) a ∧ u.card = n
  have hP : ∃ n, P n := by
    rcases exists_finset_of_isAlgebraic_adjoin (K := K) (s := s) (a := a) ha_alg with
      ⟨u, hus, hua⟩
    exact ⟨u.card, u, hus, hua, rfl⟩
  let u : Finset L := Classical.choose (Nat.find_spec hP)
  have hu := Classical.choose_spec (Nat.find_spec hP)
  refine
    { support := u
      subset_base := hu.1
      algebraic_support := hu.2.1
      minimal := ?_
      exchange := trivial }
  intro v hvs hva
  have hvP : P v.card := ⟨v, hvs, hva, rfl⟩
  have hmin := Nat.find_min' hP hvP
  have hcard : u.card = Nat.find hP := hu.2.2
  simpa [hcard] using hmin

/-- Steinitz finite replacement existence.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Koerper*,
`Sec. 22`, Satz `8` (finite replacement/exchange for equivalent irreducible
systems). This is the remaining upstream boundary: it keeps only the existence
of a replacement set; cardinal inequalities are derived below. -/
axiom exists_finite_exchange_replacement
    {U W : Finset L}
    (hU : AlgebraicIndependent K (fun x : (U : Set L) => (x : L)))
    (hW : AlgebraicIndependent K (fun x : (W : Set L) => (x : L)))
    (hdep : ∀ w ∈ (W : Set L), IsAlgebraic (IntermediateField.adjoin K (U : Set L)) w) :
    ∃ V : Finset L,
      V ⊆ U ∧ Disjoint V W ∧
      (W ∪ V).card = U.card ∧
      AlgebraicIndependent K (fun x : ((W ∪ V : Finset L) : Set L) => (x : L))

/-- Finite exchange / replacement, with the cardinal inequality derived from
the replacement set. -/
theorem finite_exchange_replacement
    {U W : Finset L}
    (hU : AlgebraicIndependent K (fun x : (U : Set L) => (x : L)))
    (hW : AlgebraicIndependent K (fun x : (W : Set L) => (x : L)))
    (hdep : ∀ w ∈ (W : Set L), IsAlgebraic (IntermediateField.adjoin K (U : Set L)) w) :
    W.card <= U.card ∧
      ∃ V : Finset L,
        V ⊆ U ∧ Disjoint V W ∧
        (W ∪ V).card = U.card ∧
        AlgebraicIndependent K (fun x : ((W ∪ V : Finset L) : Set L) => (x : L)) := by
  rcases exists_finite_exchange_replacement (K := K) (U := U) (W := W) hU hW hdep with
    ⟨V, hVU, hVW, hcard, hVWai⟩
  refine ⟨?_, ⟨V, hVU, hVW, hcard, hVWai⟩⟩
  have hle : W.card ≤ (W ∪ V).card := Finset.card_le_card Finset.subset_union_left
  exact hcard ▸ hle

/-- Cardinal comparison over a finite independent support.

The finite-subset bound is obtained from finite exchange, then upgraded by
`Cardinal.card_le_of`; this is Steinitz (1910), *Algebraische Theorie der
Koerper*, `Sec. 22`, Satz `9`. -/
theorem cardinal_le_of_isAlgebraic_over_finite_independent
    {s t : Set L}
    (hsfin : s.Finite)
    (hs : AlgebraicIndependent K ((↑) : s -> L))
    (ht : AlgebraicIndependent K ((↑) : t -> L))
    (hdep : ∀ a ∈ t, IsAlgebraic (IntermediateField.adjoin K s) a) :
    Cardinal.mk t <= Cardinal.mk s := by
  classical
  letI : Fintype s := hsfin.fintype
  rw [Cardinal.mk_fintype s]
  apply Cardinal.card_le_of (α := t) (n := Fintype.card s)
  intro u
  let U : Finset L := hsfin.toFinset
  let W : Finset L := u.map (Function.Embedding.subtype (fun x : L => x ∈ t))
  have hU : AlgebraicIndependent K (fun x : (U : Set L) => (x : L)) := by
    change AlgebraicIndependent K (Subtype.val : ↥(U : Set L) → L)
    rw [show (U : Set L) = s from hsfin.coe_toFinset]
    exact hs
  have hW : AlgebraicIndependent K (fun x : (W : Set L) => (x : L)) := by
    change AlgebraicIndependent K (Subtype.val : ↥(W : Set L) → L)
    simpa [W] using algebraicIndependent_finset_map_embedding_subtype (R := K) (s := t) ht u
  have hdepW : ∀ w ∈ (W : Set L), IsAlgebraic (IntermediateField.adjoin K (U : Set L)) w := by
    intro w hw
    have hw' : w ∈ t := by
      simp only [W, Finset.mem_coe, Finset.mem_map] at hw
      rcases hw with ⟨x, _hx, rfl⟩
      exact x.2
    have hsU : (U : Set L) = s := by exact hsfin.coe_toFinset
    rw [hsU]
    exact hdep w hw'
  have hleWU : W.card <= U.card :=
    (finite_exchange_replacement (K := K) (U := U) (W := W) hU hW hdepW).1
  have hWcard : W.card = u.card := by
    simp [W]
  have hUcard : U.card = Fintype.card s := by
    exact hsfin.card_toFinset
  omega

end MathlibExpansion.FieldTheory.Transcendence
