import Mathlib.RingTheory.AlgebraicIndependent.RankAndCardinality
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

/-!
# Steinitz transcendence degree facade

This file isolates the first-class transcendence-degree invariant around
Steinitz's `§23` package.  Mathlib already supplies transcendence bases,
the rational-function model of an algebraically independent family, and
algebraicity over the generated intermediate field.  The remaining hard
gap is the invariant theorem that any two transcendence bases of the same
extension are equipotent, plus the tower law stated on the invariant.
-/

universe u v w z

noncomputable section

namespace MathlibExpansion.FieldTheory.Transcendence

open AlgebraicIndependent Cardinal

/-- Steinitz's invariant theorem: any two transcendence bases of the same
extension have equipotent index types.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Körper*,
Part IV, `§23`, theorem `3`, printed p. 299.  Steinitz explicitly invokes
Bernstein's theorem in the proof.  Mathlib v4.17 has transcendence bases
and Cantor-Bernstein, but not the field-theoretic bridge from maximal
algebraic independence to mutual embeddings of the two bases. -/
axiom IsTranscendenceBasis.equivIndexOfSameExtension
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type w} {κ : Type z} {x : ι -> E} {y : κ -> E}
    (hx : IsTranscendenceBasis F x)
    (hy : IsTranscendenceBasis F y) :
    Nonempty (ι ≃ κ)

/-- The transcendence degree of `E/F`, implemented as the cardinality of
one chosen Mathlib transcendence basis.

Independence of this choice is supplied by
`IsTranscendenceBasis.cardinalMk_eq_transcendenceDegree`, whose only
remaining mathematical input is Steinitz's `§23`, theorem `3`. -/
def transcendenceDegree
    (F : Type u) (E : Type v) [Field F] [Field E] [Algebra F E] :
    Cardinal.{v} :=
  Cardinal.mk
    (Classical.choose (exists_isTranscendenceBasis' F (A := E) (algebraMap F E).injective))

/-- A transcendence basis has cardinality equal to `transcendenceDegree`.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Körper*,
Part IV, `§23`, theorem `3`, printed p. 299, followed by the definition
paragraph naming this cardinality the transcendence degree. -/
theorem IsTranscendenceBasis.cardinalMk_eq_transcendenceDegree
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type w} {x : ι -> E} (hx : IsTranscendenceBasis F x) :
    Cardinal.lift.{v} #ι = Cardinal.lift.{w} (transcendenceDegree F E) := by
  let b := exists_isTranscendenceBasis' F (A := E) (algebraMap F E).injective
  let κ := Classical.choose b
  let y := Classical.choose (Classical.choose_spec b)
  have hy : IsTranscendenceBasis F y := Classical.choose_spec (Classical.choose_spec b)
  have hnon : Nonempty (ι ≃ κ) := IsTranscendenceBasis.equivIndexOfSameExtension hx hy
  simpa [transcendenceDegree, b, κ] using (Cardinal.lift_mk_eq.{w, v, 0}).mpr hnon

/-- Steinitz's tower law for transcendence degree.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Körper*,
Part IV, `§23`, theorem `4`, printed p. 300.  This is kept as the
sharpened invariant-level boundary: Mathlib has substantial chosen-basis
cardinality tools, but not the theorem stated for the named invariant. -/
axiom transcendenceDegree_tower
    (F : Type u) (K : Type v) (E : Type w) [Field F] [Field K] [Field E]
    [Algebra F K] [Algebra K E] [Algebra F E] [IsScalarTower F K E] :
    Cardinal.lift.{v} (transcendenceDegree F E) =
      Cardinal.lift.{w} (transcendenceDegree F K) +
        Cardinal.lift.{v} (transcendenceDegree K E)

/-- Every algebraic extension over the rational-function field generated by
a transcendence basis is represented by an intermediate field of the chosen
algebraic closure.

Primary source: E. Steinitz (1910), *Algebraische Theorie der Körper*,
Part IV, `§23`, theorem `5`, printed p. 300.  The proof below composes
Mathlib's rational-function presentation of an algebraically independent
family, algebraicity over the generated intermediate field, and
`IsAlgClosed.lift`. -/
theorem exists_intermediateField_of_abs_trdeg
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type w} {x : ι -> E}
    (hx : IsTranscendenceBasis F x) :
    ∃ L : IntermediateField (FractionRing (MvPolynomial ι F))
        (AlgebraicClosure (FractionRing (MvPolynomial ι F))),
      Nonempty (E ≃+* L) := by
  let K := FractionRing (MvPolynomial ι F)
  let Kx := IntermediateField.adjoin F (Set.range x)
  letI : Algebra K E :=
    (((IntermediateField.adjoin F (Set.range x)).val.comp
      hx.1.aevalEquivField.toAlgHom).toRingHom.toAlgebra)
  haveI hKxE : Algebra.IsAlgebraic Kx E := hx.isAlgebraic_field
  haveI hKE : Algebra.IsAlgebraic K E := by
    constructor
    intro a
    let e : K ≃+* Kx := hx.1.aevalEquivField.toRingEquiv
    have hcomp : (algebraMap Kx E).comp (e : K →+* Kx) =
        ((RingEquiv.refl E : E ≃+* E) : E →+* E).comp (algebraMap K E) := by
      ext z
      rfl
    exact (isAlgebraic_ringHom_iff_of_comp_eq e (RingEquiv.refl E)
      (RingEquiv.refl E).injective hcomp).mp
      (Algebra.IsAlgebraic.isAlgebraic (R := Kx) a)
  let f : E →ₐ[K] AlgebraicClosure K := IsAlgClosed.lift
  refine ⟨f.fieldRange, ?_⟩
  exact ⟨(AlgEquiv.ofInjectiveField f).toRingEquiv⟩

end MathlibExpansion.FieldTheory.Transcendence
