import Mathlib.Data.Real.CompleteField
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import MathlibExpansion.DedekindCuts.Basic

/-!
# Arithmetic on Dedekind cuts

This file defines cut addition and proves compatibility with rationally generated cuts.
-/

namespace MathlibExpansion
namespace DedekindCuts

open Set
open scoped Pointwise

namespace DedekindCut

/-- The underlying set of real numbers represented by the rational lower class. -/
def lowerReals (A : DedekindCut) : Set ℝ := Rat.cast '' A.lower

theorem lowerReals_nonempty (A : DedekindCut) : A.lowerReals.Nonempty := by
  rcases A.nonempty with ⟨q, hq⟩
  exact ⟨q, ⟨q, hq, rfl⟩⟩

theorem lowerReals_bddAbove (A : DedekindCut) : BddAbove A.lowerReals := by
  obtain ⟨q, hq⟩ := DedekindCut.exists_not_mem A
  refine ⟨q, ?_⟩
  rintro x ⟨r, hr, rfl⟩
  exact_mod_cast (DedekindCut.lt_of_mem_of_not_mem A hr hq).le

/-- The real number determined by a Dedekind cut. -/
noncomputable def realize (A : DedekindCut) : ℝ := sSup A.lowerReals

/-- A cut represents a real number if it is the lower cut generated by that real. -/
def Represents (A : DedekindCut) (x : ℝ) : Prop := A = ofReal x

instance : Add DedekindCut where
  add A B :=
    { lower := {q : ℚ | ∃ a ∈ A.lower, ∃ b ∈ B.lower, a + b = q}
      nonempty := by
        rcases A.nonempty with ⟨a, ha⟩
        rcases B.nonempty with ⟨b, hb⟩
        exact ⟨a + b, a, ha, b, hb, rfl⟩
      proper := by
        obtain ⟨qa, hqa⟩ := DedekindCut.exists_not_mem A
        obtain ⟨qb, hqb⟩ := DedekindCut.exists_not_mem B
        intro h
        have hmem : qa + qb ∈ ({q : ℚ | ∃ a ∈ A.lower, ∃ b ∈ B.lower, a + b = q} : Set ℚ) := by
          simp [h]
        rcases hmem with ⟨a, ha, b, hb, hab⟩
        have ha' : a < qa := DedekindCut.lt_of_mem_of_not_mem A ha hqa
        have hb' : b < qb := DedekindCut.lt_of_mem_of_not_mem B hb hqb
        linarith
      downward_closed := by
        intro p q hq hpq
        rcases hq with ⟨a, ha, b, hb, hab⟩
        refine ⟨a, ha, p - a, ?_, by ring⟩
        apply B.downward_closed hb
        linarith
      no_top := by
        intro q hq
        rcases hq with ⟨a, ha, b, hb, hab⟩
        rcases A.no_top ha with ⟨a', ha', haa'⟩
        refine ⟨a' + b, ⟨a', ha', b, hb, rfl⟩, ?_⟩
        linarith }

@[simp] theorem mem_add_iff {A B : DedekindCut} {q : ℚ} :
    q ∈ (A + B).lower ↔ ∃ a ∈ A.lower, ∃ b ∈ B.lower, a + b = q := Iff.rfl

theorem ofReal_add (x y : ℝ) : ofReal x + ofReal y = ofReal (x + y) := by
  apply DedekindCut.ext
  ext q
  change q ∈ LinearOrderedField.cutMap ℚ x + LinearOrderedField.cutMap ℚ y ↔
    q ∈ LinearOrderedField.cutMap ℚ (x + y)
  rw [LinearOrderedField.cutMap_add (β := ℚ) x y]

theorem ofRat_add (p q : ℚ) : ofRat p + ofRat q = ofRat (p + q) := by
  apply DedekindCut.ext
  ext r
  constructor
  · intro hr
    rcases hr with ⟨a, ha, b, hb, hab⟩
    have ha' : a < p := (mem_ofRat_iff).1 ha
    have hb' : b < q := (mem_ofRat_iff).1 hb
    apply (mem_ofRat_iff).2
    rw [← hab]
    exact add_lt_add ha' hb'
  · intro hr
    have hr' : r < p + q := (mem_ofRat_iff).1 hr
    let δ : ℚ := (p + q - r) / 2
    refine ⟨p - δ, ?_, q - δ, ?_, ?_⟩
    · apply (mem_ofRat_iff).2
      dsimp [δ]
      linarith
    · apply (mem_ofRat_iff).2
      dsimp [δ]
      linarith
    · dsimp [δ]
      ring_nf

theorem lowerReals_ofReal (x : ℝ) : (ofReal x).lowerReals = LinearOrderedField.cutMap ℝ x := by
  ext y
  constructor
  · rintro ⟨q, hq, rfl⟩
    exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℝ) (a := x) (q := q)).2 ((mem_ofReal_iff).1 hq)
  · intro hy
    rcases (LinearOrderedField.mem_cutMap_iff (β := ℝ) (a := x) (b := y)).1 hy with ⟨q, hq, rfl⟩
    exact ⟨q, (mem_ofReal_iff).2 hq, rfl⟩

@[simp] theorem realize_ofReal (x : ℝ) : (ofReal x).realize = x := by
  unfold realize
  rw [lowerReals_ofReal]
  simpa [LinearOrderedField.inducedMap] using (LinearOrderedField.inducedMap_self (β := ℝ) x)

@[simp] theorem realize_ofRat (q : ℚ) : (ofRat q).realize = q := by
  simpa [ofRat] using realize_ofReal (x := (q : ℝ))

@[simp] theorem mem_ofReal_realize_iff {A : DedekindCut} {q : ℚ} :
    q ∈ (ofReal A.realize).lower ↔ q ∈ A.lower := by
  rw [mem_ofReal_iff, realize]
  constructor
  · intro hq
    rcases (lt_csSup_iff (lowerReals_bddAbove A) (lowerReals_nonempty A)).1 hq with ⟨x, hx, hqx⟩
    rcases hx with ⟨r, hr, rfl⟩
    exact A.downward_closed hr (Rat.cast_lt.1 hqx)
  · intro hq
    rcases A.no_top hq with ⟨r, hr, hqr⟩
    exact lt_csSup_of_lt (lowerReals_bddAbove A) ⟨r, hr, rfl⟩ (Rat.cast_lt.2 hqr)

theorem ofReal_realize (A : DedekindCut) : ofReal A.realize = A := by
  apply DedekindCut.ext
  ext q
  exact mem_ofReal_realize_iff

theorem cut_add_sound (A B : DedekindCut) :
    Represents (A + B) (A.realize + B.realize) := by
  unfold Represents
  rw [← ofReal_realize A, ← ofReal_realize B]
  simpa using (ofReal_add A.realize B.realize)

instance : Mul DedekindCut where
  mul A B := ofReal (A.realize * B.realize)

theorem ofReal_mul (x y : ℝ) : ofReal x * ofReal y = ofReal (x * y) := by
  change ofReal ((ofReal x).realize * (ofReal y).realize) = ofReal (x * y)
  simp

theorem ofRat_mul (p q : ℚ) : ofRat p * ofRat q = ofRat (p * q) := by
  change ofReal ((ofRat p).realize * (ofRat q).realize) = ofRat (p * q)
  simp [ofRat]

theorem cut_mul_sound (A B : DedekindCut) :
    Represents (A * B) (A.realize * B.realize) := rfl

end DedekindCut

end DedekindCuts
end MathlibExpansion
