import Mathlib.Algebra.Order.CompleteField
import Mathlib.Data.Real.Archimedean
import Mathlib.Data.Real.Basic

/-!
# Basic Dedekind cuts

This file packages Dedekind cuts of `ℚ` as bundled lower sets, using the same
strict-lower convention as Mathlib's `cutMap`.
-/

namespace MathlibExpansion
namespace DedekindCuts

open Set

/-- A Dedekind cut of `ℚ`, presented by its lower class. -/
structure DedekindCut where
  lower : Set ℚ
  nonempty : lower.Nonempty
  proper : lower ≠ Set.univ
  downward_closed : ∀ {p q : ℚ}, q ∈ lower → p < q → p ∈ lower
  no_top : ∀ {q : ℚ}, q ∈ lower → ∃ r ∈ lower, q < r

namespace DedekindCut

@[ext] theorem ext {A B : DedekindCut} (h : A.lower = B.lower) : A = B := by
  cases A
  cases B
  cases h
  rfl

theorem exists_not_mem (A : DedekindCut) : ∃ q : ℚ, q ∉ A.lower := by
  by_contra h
  apply A.proper
  ext q
  constructor
  · intro _hq
    trivial
  · intro _hq
    by_contra hq
    exact h ⟨q, hq⟩

theorem lt_of_mem_of_not_mem (A : DedekindCut) {p q : ℚ}
    (hp : p ∈ A.lower) (hq : q ∉ A.lower) : p < q := by
  by_contra hpq
  have hle : q ≤ p := le_of_not_gt hpq
  by_cases hqp : q = p
  · exact hq (hqp ▸ hp)
  · exact hq (A.downward_closed hp (lt_of_le_of_ne hle hqp))

end DedekindCut

open DedekindCut

/-- The cut determined by a real number. -/
def ofReal (x : ℝ) : DedekindCut where
  lower := LinearOrderedField.cutMap ℚ x
  nonempty := LinearOrderedField.cutMap_nonempty ℚ x
  proper := by
    intro h
    have hbdd : BddAbove (Set.univ : Set ℚ) := by
      simpa [h] using LinearOrderedField.cutMap_bddAbove ℚ x
    exact not_bddAbove_univ hbdd
  downward_closed := by
    intro p q hq hpq
    have hq' : (q : ℝ) < x := by
      simpa using (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := q)).1 hq
    apply (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := p)).2
    exact (Rat.cast_lt.2 hpq).trans hq'
  no_top := by
    intro q hq
    have hq' : (q : ℝ) < x := by
      simpa using (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := q)).1 hq
    obtain ⟨r, hqr, hrx⟩ := exists_rat_btwn hq'
    refine ⟨r, ?_, ?_⟩
    exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := r)).2 hrx
    exact_mod_cast hqr

/-- The cut generated by a rational number. -/
def ofRat (q : ℚ) : DedekindCut := ofReal q

@[simp] theorem mem_ofReal_iff {x : ℝ} {q : ℚ} :
    q ∈ (ofReal x).lower ↔ (q : ℝ) < x := by
  exact LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := q)

@[simp] theorem mem_ofRat_iff {p q : ℚ} : p ∈ (ofRat q).lower ↔ p < q := by
  simpa [ofRat, ofReal] using
    (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := (q : ℝ)) (q := p))

/-- A cut is rationally generated if it is the cut of some rational. -/
def GeneratedByRat (A : DedekindCut) : Prop := ∃ q : ℚ, A = ofRat q

theorem generatedByRat_ofRat (q : ℚ) : GeneratedByRat (ofRat q) := ⟨q, rfl⟩

/-- The right class of a cut has least element `q`. -/
def HasLeastUpper (A : DedekindCut) (q : ℚ) : Prop :=
  q ∉ A.lower ∧ ∀ ⦃r : ℚ⦄, r ∉ A.lower → q ≤ r

theorem generatedByRat_iff_exists_leastUpper (A : DedekindCut) :
    GeneratedByRat A ↔ ∃ q : ℚ, HasLeastUpper A q := by
  constructor
  · rintro ⟨q, rfl⟩
    refine ⟨q, ?_⟩
    constructor
    · simpa [mem_ofRat_iff]
    · intro r hr
      exact le_of_not_gt (by simpa [mem_ofRat_iff] using hr)
  · rintro ⟨q, hq⟩
    refine ⟨q, DedekindCut.ext ?_⟩
    ext p
    constructor
    · intro hp
      exact (mem_ofRat_iff).2 (DedekindCut.lt_of_mem_of_not_mem A hp hq.1)
    · intro hp
      have hpq : p < q := (mem_ofRat_iff).1 hp
      by_contra hpmem
      exact not_lt_of_ge (hq.2 hpmem) hpq

theorem ofReal_injective : Function.Injective ofReal := by
  intro x y hxy
  by_contra hneq
  have hLower : (ofReal x).lower = (ofReal y).lower := congrArg DedekindCut.lower hxy
  rcases lt_or_gt_of_ne hneq with hlt | hgt
  · obtain ⟨q, hxq, hqy⟩ := exists_rat_btwn hlt
    have hy : q ∈ (ofReal y).lower := by
      exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := y) (q := q)).2 hqy
    have hx : q ∉ (ofReal x).lower := by
      intro hq
      have : (q : ℝ) < x := by
        exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := q)).1 hq
      exact not_lt_of_ge hxq.le this
    have : q ∈ (ofReal x).lower := by simpa [hLower] using hy
    exact hx this
  · obtain ⟨q, hyq, hqx⟩ := exists_rat_btwn hgt
    have hx : q ∈ (ofReal x).lower := by
      exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := x) (q := q)).2 hqx
    have hy : q ∉ (ofReal y).lower := by
      intro hq
      have : (q : ℝ) < y := by
        exact (LinearOrderedField.coe_mem_cutMap_iff (β := ℚ) (a := y) (q := q)).1 hq
      exact not_lt_of_ge hyq.le this
    have : q ∈ (ofReal y).lower := by simpa [hLower] using hx
    exact hy this

end DedekindCuts
end MathlibExpansion
