import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.Localization.AtPrime
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.Polynomial.Basic

/-!
# T20c_late_01 KDH — Krull dimension and ideal height (B3 breach)

**Classification.** `breach_candidate` / `B3` per Step 5 verdict. The
carrier primitives exist (`ringKrullDim`, `Ideal.minimalPrimes`), but
polynomial dimension growth, principal-ideal height control, local
dimension comparison, and regular-local packaging are all still missing
theorem surfaces under the Atiyah-Macdonald Ch. 11 phrasing.

**Dispatch note (cycle-2, 2026-04-24).** Cycle-2 upgrades KDH_04 … KDH_07
to SHARP upstream-narrow axioms with real mathematical signatures. No
vacuous `True` bodies.

**Citation.** Atiyah & Macdonald (1969), Ch. 11, pp. 112–120. Historical
parent: Krull, "Primidealketten in allgemeinen Ringbereichen",
Sitz. Heid. Akad. Wiss. (1928); Nagata, *Local Rings*, Interscience (1962),
Ch. II.
-/

namespace MathlibExpansion
namespace Roots
namespace AtiyahMacdonald
namespace T20cLate01_KDH

/-- **KDH_04** polynomial dimension growth (2026-04-24). For a Noetherian
commutative ring `R`, the Krull dimension of `R[X]` equals `ringKrullDim R + 1`.

Sharp upstream-narrow axiom; proof route is Atiyah-Macdonald Ch. 11 Cor. 11.7
(Noetherian case).

Citation: Atiyah-Macdonald Ch. 11 Cor. 11.7 + Ex. 11.11, pp. 117–118.
Historical: Seidenberg (1953). -/
axiom krullDim_polynomial_succ
    {R : Type*} [CommRing R] [IsNoetherianRing R] :
    ringKrullDim (Polynomial R) = ringKrullDim R + 1

/-- **KDH_05** local dimension is finite (2026-04-24). For a Noetherian
local ring `(R, 𝔪)`, the Krull dimension `ringKrullDim R` is a natural
number (equivalently: coincides with the degree of the Hilbert-Samuel
polynomial of any `𝔪`-primary ideal, the HFLD_04 content).

Sharp upstream-narrow axiom; the equality with polynomial degree is the
Hilbert-Samuel theorem (HFLD_04).

Citation: Atiyah-Macdonald Ch. 11 Thm. 11.14, p. 119. -/
axiom localDim_finite
    {R : Type*} [CommRing R] [IsLocalRing R] [IsNoetherianRing R] :
    ∃ (d : ℕ), ringKrullDim R = (d : WithBot ℕ∞)

/-- **KDH_06** Krull principal-ideal theorem (Hauptidealsatz, 2026-04-24).
In a Noetherian commutative ring `R`, for any `a : R` and any prime `P`
minimal over the principal ideal `(a)`, the height of `P` (the Krull
dimension of the localization at `P`) is at most 1.

Sharp upstream-narrow axiom; proof route is Atiyah-Macdonald Ch. 11 §11.3.

Citation: Atiyah-Macdonald Ch. 11 Thm. 11.14 + Cor. 11.16, pp. 119–120.
Historical: Krull (1928). -/
axiom krull_hauptidealsatz
    {R : Type*} [CommRing R] [IsNoetherianRing R] (a : R)
    (P : Ideal R) [P.IsPrime]
    (_hP_min : P ∈ (Ideal.span ({a} : Set R)).minimalPrimes) :
    ringKrullDim (Localization.AtPrime P) ≤ (1 : WithBot ℕ∞)

/-- **KDH_07** regular-local dimension / generator bound (2026-04-24). For a
Noetherian local ring `(R, 𝔪)`, if `𝔪` can be generated by `n` elements
then `ringKrullDim R ≤ n`. This is the Krull-dimension upper bound under
a given generator witness; equality is the regular-local characterization
(RLH2_03).

Sharp upstream-narrow axiom; proof route is Krull's Hauptidealsatz
(KDH_06) applied iteratively.

Citation: Atiyah-Macdonald Ch. 11 Thm. 11.22, p. 121. -/
axiom regularLocal_dim_generator_bound
    {R : Type*} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (n : ℕ) (s : Finset R)
    (_hs_card : s.card = n)
    (_hs_span : Ideal.span (↑s : Set R) = IsLocalRing.maximalIdeal R) :
    ringKrullDim R ≤ (n : WithBot ℕ∞)

end T20cLate01_KDH
end AtiyahMacdonald
end Roots
end MathlibExpansion
