import MathlibExpansion.Dynamics.Hamiltonian.PoissonBracket

/-!
# Canonical elements and Hamilton-form evolution

On affine observables in canonical coordinates, the Hamiltonian action is just
Poisson bracketing with the Hamiltonian.  For the coordinate observables
`q_i, p_i`, this recovers the standard Hamilton-form evolution equations.
-/

namespace MathlibExpansion
namespace Dynamics
namespace Hamiltonian

open AffineObservable

section

variable {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]

/-- The Hamiltonian action generated by `H`. -/
def hamiltonianAction (H f : AffineObservable R ι) : AffineObservable R ι :=
  AffineObservable.poissonBracket f H

@[simp] theorem hamiltonianAction_qCoordinate (H : AffineObservable R ι) (i : ι) :
    hamiltonianAction H (qCoordinate (R := R) i) = constant (ι := ι) (pPart H i) := by
  classical
  apply Prod.ext
  · simp [hamiltonianAction, AffineObservable.poissonBracket, qCoordinate, constant,
      mkObservable, sum_kronecker_left, pPart, qPart]
  · apply Prod.ext
    · funext j
      simp [hamiltonianAction, AffineObservable.poissonBracket, qCoordinate, constant,
        mkObservable]
    · funext j
      simp [hamiltonianAction, AffineObservable.poissonBracket, qCoordinate, constant,
        mkObservable]

@[simp] theorem hamiltonianAction_pCoordinate (H : AffineObservable R ι) (i : ι) :
    hamiltonianAction H (pCoordinate (R := R) i) = constant (ι := ι) (-qPart H i) := by
  classical
  apply Prod.ext
  · simp [hamiltonianAction, AffineObservable.poissonBracket, pCoordinate, constant,
      mkObservable, sum_kronecker_left, sub_eq_add_neg, add_comm, pPart, qPart]
  · apply Prod.ext
    · funext j
      simp [hamiltonianAction, AffineObservable.poissonBracket, pCoordinate, constant,
        mkObservable]
    · funext j
      simp [hamiltonianAction, AffineObservable.poissonBracket, pCoordinate, constant,
        mkObservable]

/-- Concrete Hamilton-form evolution for the affine canonical coordinates. -/
theorem canonical_elements_hamilton_form (H : AffineObservable R ι) (i : ι) :
    hamiltonianAction H (qCoordinate (R := R) i) = constant (ι := ι) (pPart H i) ∧
      hamiltonianAction H (pCoordinate (R := R) i) = constant (ι := ι) (-qPart H i) := by
  exact ⟨hamiltonianAction_qCoordinate H i, hamiltonianAction_pCoordinate H i⟩

end

end Hamiltonian
end Dynamics
end MathlibExpansion
