import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.LinearAlgebra.Matrix.Transvection

namespace MathlibExpansion
namespace LinearAlgebra
namespace Matrix

open scoped MatrixGroups

variable {n : Type*} [Fintype n] [DecidableEq n] {K : Type*} [Field K]

/-- Jordan's generating set inside `GLₙ`: transvections together with invertible diagonal matrices. -/
def jordanGeneratorSet : Set (Matrix.GeneralLinearGroup n K) :=
  (Set.range fun t : Matrix.TransvectionStruct n K =>
      Matrix.GeneralLinearGroup.mkOfDetNeZero t.toMatrix (by simp)) ∪
    Set.range fun D : { D : n → K // Matrix.det (Matrix.diagonal D) ≠ 0 } =>
      Matrix.GeneralLinearGroup.mkOfDetNeZero (Matrix.diagonal D.1) D.2

/--
An element of `GLₙ` lies in the subgroup generated by transvections and invertible diagonal
matrices. This packages `Matrix.diagonal_transvection_induction_of_det_ne_zero` directly in `GLₙ`.
-/
theorem gl_mem_closure_jordanGeneratorSet (M : Matrix.GeneralLinearGroup n K) :
    M ∈ Subgroup.closure (jordanGeneratorSet (n := n) (K := K)) := by
  have hmk :
      Matrix.GeneralLinearGroup.mkOfDetNeZero (↑M)
        (show ((M : Matrix n n K).det) ≠ 0 from M.det.ne_zero) = M := by
    ext i j
    rfl
  have hmem :
      Matrix.GeneralLinearGroup.mkOfDetNeZero (↑M)
        (show ((M : Matrix n n K).det) ≠ 0 from M.det.ne_zero) ∈
          Subgroup.closure (jordanGeneratorSet (n := n) (K := K)) := by
    refine Matrix.diagonal_transvection_induction_of_det_ne_zero
      (P := fun A =>
        ∀ hA : A.det ≠ 0,
          Matrix.GeneralLinearGroup.mkOfDetNeZero A hA ∈
            Subgroup.closure (jordanGeneratorSet (n := n) (K := K)))
      ((M : Matrix n n K)) (show ((M : Matrix n n K).det) ≠ 0 from M.det.ne_zero) ?_ ?_ ?_
      (show ((M : Matrix n n K).det) ≠ 0 from M.det.ne_zero)
    · intro D hD
      exact fun _ => Subgroup.subset_closure <| Or.inr ⟨⟨D, hD⟩, rfl⟩
    · intro t
      exact fun _ => Subgroup.subset_closure <| Or.inl ⟨t, rfl⟩
    · intro A B hA hB hPA hPB hAB
      have hmul :
          Matrix.GeneralLinearGroup.mkOfDetNeZero (A * B) hAB =
            Matrix.GeneralLinearGroup.mkOfDetNeZero A hA *
              Matrix.GeneralLinearGroup.mkOfDetNeZero B hB := by
        ext i j
        rfl
      rw [hmul]
      exact Subgroup.mul_mem _ (hPA hA) (hPB hB)
  simpa [hmk] using hmem

end Matrix
end LinearAlgebra
end MathlibExpansion
