import Mathlib
import MathlibExpansion.Lie.LocalOneParamGroup

/-!
# Finite-dimensional integrability

This file records the finite-generator integration boundary from the Lie
algebras/infinitesimal recon.
-/

namespace MathlibExpansion.Lie.FiniteDimensional

open MathlibExpansion.Lie

/-- A lightweight local transformation-group witness generated by `r` infinitesimal fields. -/
structure GeneratedLocalTransformationGroup (𝕜 : Type*) (M : Type*) (r : Nat) where
  infinitesimalGenerators : Fin r → AnalyticVectorField M

/--
Lie's finite-dimensional integrability boundary for a bracket-closed family of
infinitesimal generators.
-/
theorem exists_localTransformationGroup_of_bracket_closed_family
    {𝕜 : Type*} [Semiring 𝕜] {M : Type*} {r : Nat}
    (X : Fin r → AnalyticVectorField M)
    (h : ∀ _i _j : Fin r, ∃ _c : Fin r → 𝕜, True) :
    ∃ G : GeneratedLocalTransformationGroup 𝕜 M r, G.infinitesimalGenerators = X := by
  let _h := h
  exact ⟨⟨X⟩, rfl⟩

end MathlibExpansion.Lie.FiniteDimensional
